ETL - Extract Transform Load

In [11]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/raw/bugsinpy/projects")
list_of_libraries = []
for p in DATA_DIR.iterdir():
    if p.is_dir():
        print(p.name)
        list_of_libraries.append(p)
print(len(list_of_libraries))

keras
thefuck
PySnooper
luigi
cookiecutter
scrapy
ansible
tornado
tqdm
fastapi
sanic
matplotlib
youtube-dl
httpie
spacy
black
pandas
17

In [36]:

PANDAS_DIR = DATA_DIR / "pandas"/"bugs"
list_of_pandas_bugs = []
for bugs in PANDAS_DIR.iterdir():
    if bugs.is_dir():
        list_of_pandas_bugs.append(bugs)
print(len(list_of_pandas_bugs))

169

In [37]:
##Explore first bug in pandas

bug=list_of_pandas_bugs[0]
print(bug)

../data/raw/bugsinpy/projects/pandas/bugs/135

In [38]:
with open(bug/"bug.info", 'r') as f:
    bug_info = f.read()
print(bug_info)

python_version="3.8.3"
buggy_commit_id="0df22b6"
fixed_commit_id="f41219179de69fed5c2a4b7df821394af1aa6559"
test_file="pandas/tests/extension/decimal/test_decimal.py"

In [41]:
dict_of_bugs = {}
for bug in list_of_pandas_bugs:
    dict_of_bugs[bug.name] = {}
    with open(bug/"bug.info", 'r') as f:
        bug_info = f.read()
        bug_info_lines = bug_info.splitlines()
        for line in bug_info_lines:
            key, value = line.split("=")
            value = value.strip('"')
            dict_of_bugs[bug.name][key] = value
print(dict_of_bugs)

{'135': {'python_version': '3.8.3" ', 'buggy_commit_id': '0df22b6" ', 'fixed_commit_id': 'f41219179de69fed5c2a4b7df821394af1aa6559"  ', 'test_file': 'pandas/tests/extension/decimal/test_decimal.py" '}, '61': {'python_version': '3.8.3" ', 'buggy_commit_id': '74dad82" ', 'fixed_commit_id': 'f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc"  ', 'test_file': 'pandas/tests/indexing/test_indexing.py" '}, '95': {'python_version': '3.8.3" ', 'buggy_commit_id': '036dc88" ', 'fixed_commit_id': 'c99dfea33612f44e97c2365f78c0ca6d5754a1bc"  ', 'test_file': 'pandas/tests/arithmetic/test_period.py" '}, '132': {'python_version': '3.8.3" ', 'buggy_commit_id': '221c8a7" ', 'fixed_commit_id': 'bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c"  ', 'test_file': 'pandas/tests/reductions/test_reductions.py" '}, '59': {'python_version': '3.8.3" ', 'buggy_commit_id': '292a993" ', 'fixed_commit_id': '8dd9fabd2ad9104e747084437b9ad436d5be087a"  ', 'test_file': 'pandas/tests/window/test_pairwise.py" '}, '92': {'python_version': '3.8.3" ', 'buggy_commit_id': 'f2b213c" ', 'fixed_commit_id': '511a2847f4330c54d079d04b3cac4febe0fe9915"  ', 'test_file': 'pandas/tests/frame/methods/test_asof.py" '}, '66': {'python_version': '3.8.3" ', 'buggy_commit_id': 'f5409cb" ', 'fixed_commit_id': 'd84f9eb32aea33a8f790e8e365cf226eddd5c7a7"  ', 'test_file': 'pandas/tests/series/indexing/test_xs.py" '}, '104': {'python_version': '3.8.3" ', 'buggy_commit_id': 'f738581" ', 'fixed_commit_id': '8e9b3eee812b70197341c26c40200d8a1a77ed9c"  ', 'test_file': 'pandas/tests/groupby/test_function.py" '}, '50': {'python_version': '3.8.3" ', 'buggy_commit_id': 'ebf9668" ', 'fixed_commit_id': '821aa25c9039e72da9a7b236cf2f9e7d549cbb7b"  ', 'test_file': 'pandas/tests/extension/test_categorical.py" '}, '68': {'python_version': '3.8.3" ', 'buggy_commit_id': '01582c4" ', 'fixed_commit_id': 'd28db65bdba16e9400a16469ba2707f94ae63483"  ', 'test_file': 'pandas/tests/arrays/interval/test_interval.py" '}, '103': {'python_version': '3.8.3" ', 'buggy_commit_id': 'd1f82f7" ', 'fixed_commit_id': '19578e364fb47ce10dd14174cffc3ecfea1a58cd"  ', 'test_file': 'pandas/tests/groupby/test_transform.py" '}, '57': {'python_version': '3.8.3" ', 'buggy_commit_id': '267d2d8" ', 'fixed_commit_id': '84444538a88721c5ee74de8836b716d3c1adc4b8"  ', 'test_file': 'pandas/tests/arrays/categorical/test_replace.py" '}, '168': {'python_version': '3.8.3" ', 'buggy_commit_id': '2de4fbb" ', 'fixed_commit_id': '1fa1ad91b29c5474cbb86cbcbcdcd50537cad0ae"  ', 'test_file': 'pandas/tests/groupby/test_groupby.py" '}, '157': {'python_version': '3.8.3" ', 'buggy_commit_id': 'b1c871c" ', 'fixed_commit_id': 'def01cf7bbb5ef8c9bf2e19737ea918e6a76a143"  ', 'test_file': 'pandas/tests/reshape/merge/test_merge_asof.py" '}, '150': {'python_version': '3.8.3" ', 'buggy_commit_id': '54e9b75" ', 'fixed_commit_id': 'd38627b5889db3f663cad339fe8f995af823b76b"  ', 'test_file': 'pandas/tests/dtypes/test_missing.py" '}, '159': {'python_version': '3.8.3" ', 'buggy_commit_id': 'e55b698" ', 'fixed_commit_id': '62ab439b168d972546e06d329916c6be7ddd1288"  ', 'test_file': 'pandas/tests/arithmetic/test_numeric.py" '}, '32': {'python_version': '3.8.3" ', 'buggy_commit_id': '467e1c2" ', 'fixed_commit_id': 'c82cb179affed1c1136431ce39e4c66f4f3a65c0"  ', 'test_file': 'pandas/tests/io/sas/test_xport.py" '}, '166': {'python_version': '3.8.3" ', 'buggy_commit_id': '4056ded" ', 'fixed_commit_id': 'd44fb07063e9a8bd8a209ddce35b40d8a56c8d02"  ', 'test_file': 'pandas/tests/frame/test_join.py" '}, '35': {'python_version': '3.8.3" ', 'buggy_commit_id': 'a7dd3ea" ', 'fixed_commit_id': 'f10ec595eccaf86a9f52fe9683e1181a51ba675b"  ', 'test_file': 'pandas/tests/indexes/multi/test_get_level_values.py" '}, '161': {'python_version': '3.8.3" ', 'buggy_commit_id': 'a818281" ', 'fixed_commit_id': 'ca5198a6daa7757e398112a17ccadc9e7d078d96"  ', 'test_file': 'pandas/tests/series/test_missing.py" '}, '102': {'python_version': '3.8.3" ', 'buggy_commit_id': 'efaadd5" ', 'fixed_commit_id': '765d8db7eef1befef33f4c99d3e206d26e8444c8"  ', 'test_file': 'pandas/tests/frame/test_constructors.py" '}, '69': {'python_version': '3.8.3" ', 'buggy_commit_id': '426d445" ', 'fixed_commit_id': '948f95756c79543bb089a94a85e73011a3730b2d"  ', 'test_file': 'pandas/tests/indexes/test_numeric.py" '}, '56': {'python_version': '3.8.3" ', 'buggy_commit_id': '9e69040" ', 'fixed_commit_id': 'dafec63f2e138d0451dae5b37edea2e83f9adc8a"  ', 'test_file': 'pandas/tests/indexing/test_scalar.py" '}, '105': {'python_version': '3.8.3" ', 'buggy_commit_id': '7e6125a" ', 'fixed_commit_id': 'cb5f9d1ff407f5ccef7c717e0c23bbd6ed96cf5f"  ', 'test_file': 'pandas/tests/arithmetic/test_period.py" '}, '51': {'python_version': '3.8.3" ', 'buggy_commit_id': '4800ab4" ', 'fixed_commit_id': 'ea1d8fadb95fbc7cafe036274006228400817fd4"  ', 'test_file': 'pandas/tests/reshape/merge/test_merge.py" '}, '58': {'python_version': '3.8.3" ', 'buggy_commit_id': '634a41f" ', 'fixed_commit_id': '16684f2affaf901b42a12e50f9c29e7c034ad7ea"  ', 'test_file': 'pandas/tests/arrays/categorical/test_constructors.py" '}, '133': {'python_version': '3.8.3" ', 'buggy_commit_id': '343544d" ', 'fixed_commit_id': 'c983d52e3a3a8a191359814417f375b1dc8b04c1"  ', 'test_file': 'pandas/tests/frame/test_missing.py" '}, '67': {'python_version': '3.8.3" ', 'buggy_commit_id': 'c3e32d7" ', 'fixed_commit_id': '1996b17599731b889895b0e1edf758588c068fbb"  ', 'test_file': 'pandas/tests/frame/indexing/test_indexing.py" '}, '93': {'python_version': '3.8.3" ', 'buggy_commit_id': '425c2fb" ', 'fixed_commit_id': 'bde25278ccf4fb2d751c5e99e24b2270e0d62ef7"  ', 'test_file': 'pandas/tests/indexes/period/test_indexing.py;" '}, '134': {'python_version': '3.8.3" ', 'buggy_commit_id': 'da1401b" ', 'fixed_commit_id': 'b1eb97bdfe17f477600eef19e82d65480457bbf5"  ', 'test_file': 'pandas/tests/tseries/holiday/test_calendar.py" '}, '94': {'python_version': '3.8.3" ', 'buggy_commit_id': '8803056" ', 'fixed_commit_id': '613df15047887957f5964d2a6ce59ea20b0c4c91"  ', 'test_file': 'pandas/tests/indexes/datetimes/test_constructors.py" '}, '60': {'python_version': '3.8.3" ', 'buggy_commit_id': '6bc2dca" ', 'fixed_commit_id': 'fcf7258c19b0a6a712f33fb0bcefdae426be7e7f"  ', 'test_file': 'pandas/tests/window/test_grouper.py" '}, '34': {'python_version': '3.8.3" ', 'buggy_commit_id': '02a134b" ', 'fixed_commit_id': 'cf9ec7854ecb80709804178e769425f02ddf8c64"  ', 'test_file': 'pandas/tests/resample/test_datetime_index.py" '}, '160': {'python_version': '3.8.3" ', 'buggy_commit_id': '489d1ff" ', 'fixed_commit_id': 'fb62fcf91c874e9c24fa83693c4e6e613f35f864"  ', 'test_file': 'pandas/tests/test_expressions.py" '}, '33': {'python_version': '3.8.3" ', 'buggy_commit_id': '03dacc1" ', 'fixed_commit_id': '89d8aba76a2bb930e520590d145e3d67b2046e39"  ', 'test_file': 'pandas/tests/arrays/integer/test_function.py" '}, '158': {'python_version': '3.8.3" ', 'buggy_commit_id': 'a76df79" ', 'fixed_commit_id': 'b1c871ce4b5e76b3cffe1ebd4216d36379872352"  ', 'test_file': 'pandas/tests/series/test_alter_axes.py" '}, '167': {'python_version': '3.8.3" ', 'buggy_commit_id': '6af6d51" ', 'fixed_commit_id': '226398224d260d908a1f3d0f23c16fa9ffc8f9b0"  ', 'test_file': 'pandas/tests/indexes/datetimes/test_partial_slicing.py" '}, '151': {'python_version': '3.8.3" ', 'buggy_commit_id': '6110608" ', 'fixed_commit_id': '5a227a410c520ceec2d94369a44e2ab774a40dc3"  ', 'test_file': 'pandas/tests/arrays/test_numpy.py" '}, '169': {'python_version': '3.8.3" ', 'buggy_commit_id': '4d9016e" ', 'fixed_commit_id': '01babb590cb15ef5c6e9ad890ea580a5112e6999"  ', 'test_file': 'pandas/tests/frame/test_quantile.py" '}, '156': {'python_version': '3.8.3" ', 'buggy_commit_id': '42d6ee7" ', 'fixed_commit_id': '05cc95971e56b503d4df9911a44cd60a7b74cc79"  ', 'test_file': 'pandas/tests/sparse/frame/test_frame.py" '}, '20': {'python_version': '3.8.3', 'buggy_commit_id': 'ea09d50', 'fixed_commit_id': '92afd5c2c08216e4e9c80eb6b92b1660f91846e0', 'test_file': 'pandas/tests/tseries/offsets/test_yqm_offsets.py'}, '18': {'python_version': '3.8.3', 'buggy_commit_id': 'e008a0a', 'fixed_commit_id': 'cb71376385c33270fa1922aec9eb6c49de4336f4', 'test_file': 'pandas/tests/window/test_base_indexer.py'}, '27': {'python_version': '3.8.3', 'buggy_commit_id': '6658d89', 'fixed_commit_id': '13dc13f12c0fca943979cde065b7484bb0e40d66', 'test_file': 'pandas/tests/indexes/datetimes/test_to_period.py'}, '9': {'python_version': '3.8.3', 'buggy_commit_id': 'c557ab5', 'fixed_commit_id': 'ebb727e5cd8865a7f5d6cfb4b22d3278b6bf5e6b', 'test_file': 'pandas/tests/indexes/categorical/test_indexing.py'}, '145': {'python_version': '3.8.3" ', 'buggy_commit_id': '3bd222d" ', 'fixed_commit_id': 'f08a1e62e31fc11e7e5bd7bec72b7e6d86473423"  ', 'test_file': 'pandas/tests/frame/test_arithmetic.py" '}, '11': {'python_version': '3.8.3', 'buggy_commit_id': '1c88e6a', 'fixed_commit_id': 'b7f061c3d24df943e16918ad3932e767f5639a38', 'test_file': 'pandas/tests/reshape/test_concat.py'}, '142': {'python_version': '3.8.3" ', 'buggy_commit_id': '7721f31" ', 'fixed_commit_id': '65815e6f33e25991e3d40a53c581ffb3c7daf70f"  ', 'test_file': 'pandas/tests/series/test_analytics.py" '}, '7': {'python_version': '3.8.3" ', 'buggy_commit_id': '27f365d" ', 'fixed_commit_id': '64336ff8414f8977ff94adb9a5bc000a3a4ef454"  ', 'test_file': 'pandas/tests/frame/indexing/test_indexing.py" '}, '29': {'python_version': '3.8.3', 'buggy_commit_id': '6e3537d', 'fixed_commit_id': '4334482c348c3adc69683c8332295e22092c1b57', 'test_file': 'pandas/tests/arrays/interval/test_interval.py;pandas/tests/series/methods/test_convert_dtypes.py'}, '16': {'python_version': '3.8.3', 'buggy_commit_id': 'f159734', 'fixed_commit_id': '74e8607cb163b76ccf272ac72ae6b7848fe930c8', 'test_file': 'pandas/tests/arithmetic/test_period.py'}, '129': {'python_version': '3.8.3" ', 'buggy_commit_id': '5b580fb" ', 'fixed_commit_id': '82c9547ddcaf2fd70e00f1368731f14a03bbac88"  ', 'test_file': 'pandas/tests/arithmetic/test_timedelta64.py" '}, '42': {'python_version': '3.8.3" ', 'buggy_commit_id': 'b3a0fe4" ', 'fixed_commit_id': '05780a760400e42ce1b00200dd8204ae4f94044a"  ', 'test_file': 'pandas/tests/util/test_assert_frame_equal.py;pandas/tests/util/test_assert_series_equal.py" '}, '89': {'python_version': '3.8.3" ', 'buggy_commit_id': '0dc317f" ', 'fixed_commit_id': 'feaa5033b7810f7775fd4806c27b2f9f1e9b5051"  ', 'test_file': 'pandas/tests/frame/test_reshape.py" '}, '116': {'python_version': '3.8.3" ', 'buggy_commit_id': '9333e3d" ', 'fixed_commit_id': 'c4fa6a52f7737aecda08f6b0f2d6c27476298ae1"  ', 'test_file': 'pandas/tests/reshape/merge/test_merge_asof.py" '}, '45': {'python_version': '3.8.3" ', 'buggy_commit_id': '74c5306" ', 'fixed_commit_id': '74f6579941fbe71cf7c033f53977047ac872e469"  ', 'test_file': 'pandas/tests/frame/test_constructors.py" '}, '111': {'python_version': '3.8.3" ', 'buggy_commit_id': '28715a7" ', 'fixed_commit_id': '27836e93dc3c9d55c60282ccb15c88c42a340d87"  ', 'test_file': 'pandas/tests/indexing/test_categorical.py;pandas/tests/indexing/test_floats.py" '}, '73': {'python_version': '3.8.3" ', 'buggy_commit_id': 'f1d7ac6" ', 'fixed_commit_id': '6f93898d32c0f1fdb382d1e9dee434c158998374"  ', 'test_file': 'pandas/tests/frame/test_arithmetic.py" '}, '118': {'python_version': '3.8.3" ', 'buggy_commit_id': '6f1accd" ', 'fixed_commit_id': '76e39ebcf584042fab4f224a6bd2c903bb0c8aff"  ', 'test_file': 'pandas/tests/reshape/test_melt.py" '}, '87': {'python_version': '3.8.3" ', 'buggy_commit_id': '641346c" ', 'fixed_commit_id': 'a890239b7020dec714d9819b718d83f786bfda34"  ', 'test_file': 'pandas/tests/reshape/test_pivot.py" '}, '127': {'python_version': '3.8.3" ', 'buggy_commit_id': 'f7d6b58" ', 'fixed_commit_id': '710d82c0d393c9031e469ec0371660d8187b7dc3"  ', 'test_file': 'pandas/tests/series/test_timeseries.py" '}, '80': {'python_version': '3.8.3" ', 'buggy_commit_id': 'd0d93db" ', 'fixed_commit_id': '351760c0655b6c383e449cf857b9a718e3545229"  ', 'test_file': 'pandas/tests/arrays/sparse/test_arithmetics.py" '}, '74': {'python_version': '3.8.3" ', 'buggy_commit_id': '9a211aa" ', 'fixed_commit_id': '839e7f1416148caff518a5b75327a2480a2bbbb4"  ', 'test_file': 'pandas/tests/indexes/timedeltas/test_constructors.py" '}, '120': {'python_version': '3.8.3" ', 'buggy_commit_id': '2b0cac7" ', 'fixed_commit_id': 'c5a1f9e2c373ced9ef2f02ab64d11eaa7b4248f2"  ', 'test_file': 'pandas/tests/groupby/test_categorical.py" '}, '6': {'python_version': '3.8.3', 'buggy_commit_id': '21a10d1', 'fixed_commit_id': '8cd8ed3657e52ad9f67e17b7f5c20f7340ab6a2c', 'test_file': 'pandas/tests/groupby/test_size.py'}, '28': {'python_version': '3.8.3', 'buggy_commit_id': '40fd73a', 'fixed_commit_id': 'ef9b9387c88cf12b20dd8656dfedfc236e0f3352', 'test_file': 'pandas/tests/test_strings.py'}, '143': {'python_version': '3.8.3" ', 'buggy_commit_id': 'c13c13b" ', 'fixed_commit_id': 'df918becf698741861da0e9b7e810d477b0eb194"  ', 'test_file': 'pandas/tests/frame/test_indexing.py;pandas/tests/indexes/test_range.py" '}, '17': {'python_version': '3.8.3', 'buggy_commit_id': '1e5ff23', 'fixed_commit_id': 'afb04645b5b3361814f7d00ef68ce8d68e19ddb8', 'test_file': 'pandas/tests/indexes/datetimes/test_insert.py'}, '144': {'python_version': '3.8.3" ', 'buggy_commit_id': 'b106108" ', 'fixed_commit_id': 'ffe6cfdbf82d663c3f77567bde11f1666de1df38"  ', 'test_file': 'pandas/tests/plotting/test_series.py" '}, '1': {'python_version': '3.8.3', 'buggy_commit_id': '3fd150c', 'fixed_commit_id': 'e41ee47a90bb1d8a1fa28fcefcd45ed8ef5cb946', 'test_file': 'pandas/tests/dtypes/test_dtypes.py'}, '10': {'python_version': '3.8.3', 'buggy_commit_id': 'de8ca78', 'fixed_commit_id': 'e1ee2b0679e5999c993a787606d30e75faaba7a2', 'test_file': 'pandas/tests/series/methods/test_update.py'}, '19': {'python_version': '3.8.3', 'buggy_commit_id': '17dc6b0', 'fixed_commit_id': 'c6a1638bcd99df677a8f76f036c0b30027eb243c', 'test_file': 'pandas/tests/indexing/multiindex/test_loc.py;pandas/tests/indexing/multiindex/test_slice.py;pandas/tests/series/indexing/test_getitem.py'}, '26': {'python_version': '3.8.3', 'buggy_commit_id': '13dc13f', 'fixed_commit_id': '70ca24680d3e51fa4b957366e8093b3cc755462d', 'test_file': 'pandas/tests/arrays/categorical/test_analytics.py'}, '8': {'python_version': '3.8.3', 'buggy_commit_id': 'ddbeca6', 'fixed_commit_id': 'd09f20e29bdfa82f5efc071986e2633001d552f6', 'test_file': 'pandas/tests/frame/methods/test_replace.py'}, '21': {'python_version': '3.8.3', 'buggy_commit_id': '4071c3b', 'fixed_commit_id': '56d0934092b8296c90f940c56fce3b731e0de81b', 'test_file': 'pandas/tests/series/indexing/test_boolean.py;pandas/tests/series/indexing/test_getitem.py'}, '75': {'python_version': '3.8.3" ', 'buggy_commit_id': '2038d7a" ', 'fixed_commit_id': '9a211aae9f710db23c9113aea0251e2758904755"  ', 'test_file': 'pandas/tests/indexes/period/test_indexing.py" '}, '81': {'python_version': '3.8.3" ', 'buggy_commit_id': 'b529857" ', 'fixed_commit_id': '339edcdb7ecc6edc6fde1b7d1413dbb746d2bcca"  ', 'test_file': 'pandas/tests/arrays/test_integer.py" '}, '121': {'python_version': '3.8.3" ', 'buggy_commit_id': 'ad4c4d5" ', 'fixed_commit_id': '958756af5cb40658e975a70d29089b68aea93040"  ', 'test_file': 'pandas/tests/frame/test_replace.py" '}, '119': {'python_version': '3.8.3" ', 'buggy_commit_id': '3f69d62" ', 'fixed_commit_id': 'e0bd4d5dd07cc481cb52de3cf3c7bf199cb2df07"  ', 'test_file': 'pandas/tests/reshape/test_pivot.py" '}, '86': {'python_version': '3.8.3" ', 'buggy_commit_id': '55cfabb" ', 'fixed_commit_id': 'f792d8c50ee456aa8aa2ae406d8e6b8843f45614"  ', 'test_file': 'pandas/tests/reshape/test_pivot.py" '}, '72': {'python_version': '3.8.3" ', 'buggy_commit_id': 'a9b61a9" ', 'fixed_commit_id': '0c50950f2a7e32887eff6be5979f09772091e1de"  ', 'test_file': 'pandas/tests/frame/indexing/test_categorical.py" '}, '126': {'python_version': '3.8.3" ', 'buggy_commit_id': '29be383" ', 'fixed_commit_id': 'e639af2afd18b90ab9063df9c1927ae1f357a418"  ', 'test_file': 'pandas/tests/frame/test_combine_concat.py" '}, '44': {'python_version': '3.8.3" ', 'buggy_commit_id': '96d22d4" ', 'fixed_commit_id': '50817487ce5b1a2c4896495509e2b53e22fa3212"  ', 'test_file': 'pandas/tests/indexes/test_base.py;pandas/tests/indexing/test_loc.py" '}, '110': {'python_version': '3.8.3" ', 'buggy_commit_id': 'cceef8e" ', 'fixed_commit_id': '96bb151fe1a5b812ecab400adcd297d14fd0e0e4"  ', 'test_file': 'pandas/tests/indexing/test_categorical.py" '}, '43': {'python_version': '3.8.3" ', 'buggy_commit_id': '81149fb" ', 'fixed_commit_id': 'be7bfe6ab7ae2cba056f61dea6c3b0226bf80082"  ', 'test_file': 'pandas/tests/frame/test_arithmetic.py" '}, '128': {'python_version': '3.8.3" ', 'buggy_commit_id': '794a1c2" ', 'fixed_commit_id': '112e6b8d054f9adc1303138533ed6506975f94db"  ', 'test_file': 'pandas/tests/io/json/test_readlines.py" '}, '88': {'python_version': '3.8.3" ', 'buggy_commit_id': '698920f" ', 'fixed_commit_id': '586bcb16023ae870b0ad7769f6d9077903705486"  ', 'test_file': 'pandas/tests/reshape/test_pivot.py" '}, '117': {'python_version': '3.8.3" ', 'buggy_commit_id': 'fc100fe" ', 'fixed_commit_id': 'f98d2b6587b74c9a640b062d94911b199d962119"  ', 'test_file': 'pandas/tests/series/test_analytics.py" '}, '153': {'python_version': '3.8.3" ', 'buggy_commit_id': 'ae22b80" ', 'fixed_commit_id': '0c0a0cfbadcf01864d499599712edc9022eea12e"  ', 'test_file': 'pandas/tests/io/formats/test_to_csv.py" '}, '38': {'python_version': '3.8.3" ', 'buggy_commit_id': 'c81d90f" ', 'fixed_commit_id': 'e7ee418fa7a519225203fef23481c5fa35834dc3"  ', 'test_file': 'pandas/tests/frame/test_reshape.py" '}, '154': {'python_version': '3.8.3" ', 'buggy_commit_id': '3f5b5c4" ', 'fixed_commit_id': 'e0c63b4cfaa821dfe310f4a8a1f84929ced5f5bd"  ', 'test_file': 'pandas/tests/groupby/test_groupby.py" '}, '36': {'python_version': '3.8.3" ', 'buggy_commit_id': 'cb41651" ', 'fixed_commit_id': '51f114b9882a5cf819efddb8be74524814f437e1"  ', 'test_file': 'pandas/tests/dtypes//test_missing.py" '}, '162': {'python_version': '3.8.3" ', 'buggy_commit_id': '341043d" ', 'fixed_commit_id': '640d9e1f5fe8ab64d1f6496b8216c28185e53225"  ', 'test_file': 'pandas/tests/reshape/test_pivot.py" '}, '31': {'python_version': '3.8.3" ', 'buggy_commit_id': '45c13a9" ', 'fixed_commit_id': '8267427bfe567eec9a098aa8c071dddcc1d289f9"  ', 'test_file': 'pandas/tests/groupby/test_function.py" '}, '165': {'python_version': '3.8.3" ', 'buggy_commit_id': '9fe8a0f" ', 'fixed_commit_id': '9b1c005142fed227081dd454eab1a414168d458e"  ', 'test_file': 'pandas/tests/arithmetic/test_datetime64.py" '}, '131': {'python_version': '3.8.3" ', 'buggy_commit_id': '73745be" ', 'fixed_commit_id': 'bf5848f111c92fc5c6c11a93a3bc2480f138f1b1"  ', 'test_file': 'pandas/tests/series/test_datetime_values.py" '}, '91': {'python_version': '3.8.3" ', 'buggy_commit_id': '5c12d4f" ', 'fixed_commit_id': 'cb9a1c7d0319c34a97247973ca96af53ead8033a"  ', 'test_file': 'pandas/tests/arrays/test_timedeltas.py" '}, '65': {'python_version': '3.8.3" ', 'buggy_commit_id': '2f70e41" ', 'fixed_commit_id': '2f9a44635bd8d468cf008f2855ce2dcfb9e90586"  ', 'test_file': 'pandas/tests/io/parser/test_encoding.py" '}, '136': {'python_version': '3.8.3" ', 'buggy_commit_id': '3954fa7" ', 'fixed_commit_id': '6241b9d3b3b8fd688cf32e45539719f1b9ec25c1"  ', 'test_file': 'pandas/tests/reshape/merge/test_merge_asof.py" '}, '62': {'python_version': '3.8.3" ', 'buggy_commit_id': '46a77f6" ', 'fixed_commit_id': '74dad82827e9b13552df2d6d3fbbeb901821b53f"  ', 'test_file': 'pandas/tests/indexing/test_indexing.py" '}, '96': {'python_version': '3.8.3" ', 'buggy_commit_id': '5e488a0" ', 'fixed_commit_id': '6d67cf9f02dd22cc870fd407f569197512700203"  ', 'test_file': 'pandas/tests/indexes/datetimes/test_date_range.py" '}, '109': {'python_version': '3.8.3" ', 'buggy_commit_id': '8b39de1" ', 'fixed_commit_id': '68b3eb4f5a7fbc223accbbeddbf03ec8ea31af00"  ', 'test_file': 'pandas/tests/arrays/categorical/test_analytics.py" '}, '100': {'python_version': '3.8.3" ', 'buggy_commit_id': '8806ed7" ', 'fixed_commit_id': '2b1b3da4c68fdaf9637d12706c5ba3de1a9b20de"  ', 'test_file': 'pandas/tests/frame/methods/tes

In [35]:
with open (PANDAS_DIR / "135" /"bug.info", 'r') as f:
    bug_info = f.read()
    for line in bug_info.splitlines():
        print(repr(line))

'python_version="3.8.3" '
'buggy_commit_id="0df22b6" '
'fixed_commit_id="f41219179de69fed5c2a4b7df821394af1aa6559"  '
'test_file="pandas/tests/extension/decimal/test_decimal.py" '

In [42]:
dict_of_bugs = {}
for bug in list_of_pandas_bugs:
    dict_of_bugs[bug.name] = {}
    with open(bug/"bug.info", 'r') as f:
        bug_info = f.read()
        bug_info_lines = bug_info.splitlines()
        for line in bug_info_lines:
            key, value = line.split("=")
            value = value.strip().strip('"')#cleaning the value by stripping whitespace and quotes
            dict_of_bugs[bug.name][key] = value
print(dict_of_bugs)

{'135': {'python_version': '3.8.3', 'buggy_commit_id': '0df22b6', 'fixed_commit_id': 'f41219179de69fed5c2a4b7df821394af1aa6559', 'test_file': 'pandas/tests/extension/decimal/test_decimal.py'}, '61': {'python_version': '3.8.3', 'buggy_commit_id': '74dad82', 'fixed_commit_id': 'f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc', 'test_file': 'pandas/tests/indexing/test_indexing.py'}, '95': {'python_version': '3.8.3', 'buggy_commit_id': '036dc88', 'fixed_commit_id': 'c99dfea33612f44e97c2365f78c0ca6d5754a1bc', 'test_file': 'pandas/tests/arithmetic/test_period.py'}, '132': {'python_version': '3.8.3', 'buggy_commit_id': '221c8a7', 'fixed_commit_id': 'bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c', 'test_file': 'pandas/tests/reductions/test_reductions.py'}, '59': {'python_version': '3.8.3', 'buggy_commit_id': '292a993', 'fixed_commit_id': '8dd9fabd2ad9104e747084437b9ad436d5be087a', 'test_file': 'pandas/tests/window/test_pairwise.py'}, '92': {'python_version': '3.8.3', 'buggy_commit_id': 'f2b213c', 'fixed_commit_id': '511a2847f4330c54d079d04b3cac4febe0fe9915', 'test_file': 'pandas/tests/frame/methods/test_asof.py'}, '66': {'python_version': '3.8.3', 'buggy_commit_id': 'f5409cb', 'fixed_commit_id': 'd84f9eb32aea33a8f790e8e365cf226eddd5c7a7', 'test_file': 'pandas/tests/series/indexing/test_xs.py'}, '104': {'python_version': '3.8.3', 'buggy_commit_id': 'f738581', 'fixed_commit_id': '8e9b3eee812b70197341c26c40200d8a1a77ed9c', 'test_file': 'pandas/tests/groupby/test_function.py'}, '50': {'python_version': '3.8.3', 'buggy_commit_id': 'ebf9668', 'fixed_commit_id': '821aa25c9039e72da9a7b236cf2f9e7d549cbb7b', 'test_file': 'pandas/tests/extension/test_categorical.py'}, '68': {'python_version': '3.8.3', 'buggy_commit_id': '01582c4', 'fixed_commit_id': 'd28db65bdba16e9400a16469ba2707f94ae63483', 'test_file': 'pandas/tests/arrays/interval/test_interval.py'}, '103': {'python_version': '3.8.3', 'buggy_commit_id': 'd1f82f7', 'fixed_commit_id': '19578e364fb47ce10dd14174cffc3ecfea1a58cd', 'test_file': 'pandas/tests/groupby/test_transform.py'}, '57': {'python_version': '3.8.3', 'buggy_commit_id': '267d2d8', 'fixed_commit_id': '84444538a88721c5ee74de8836b716d3c1adc4b8', 'test_file': 'pandas/tests/arrays/categorical/test_replace.py'}, '168': {'python_version': '3.8.3', 'buggy_commit_id': '2de4fbb', 'fixed_commit_id': '1fa1ad91b29c5474cbb86cbcbcdcd50537cad0ae', 'test_file': 'pandas/tests/groupby/test_groupby.py'}, '157': {'python_version': '3.8.3', 'buggy_commit_id': 'b1c871c', 'fixed_commit_id': 'def01cf7bbb5ef8c9bf2e19737ea918e6a76a143', 'test_file': 'pandas/tests/reshape/merge/test_merge_asof.py'}, '150': {'python_version': '3.8.3', 'buggy_commit_id': '54e9b75', 'fixed_commit_id': 'd38627b5889db3f663cad339fe8f995af823b76b', 'test_file': 'pandas/tests/dtypes/test_missing.py'}, '159': {'python_version': '3.8.3', 'buggy_commit_id': 'e55b698', 'fixed_commit_id': '62ab439b168d972546e06d329916c6be7ddd1288', 'test_file': 'pandas/tests/arithmetic/test_numeric.py'}, '32': {'python_version': '3.8.3', 'buggy_commit_id': '467e1c2', 'fixed_commit_id': 'c82cb179affed1c1136431ce39e4c66f4f3a65c0', 'test_file': 'pandas/tests/io/sas/test_xport.py'}, '166': {'python_version': '3.8.3', 'buggy_commit_id': '4056ded', 'fixed_commit_id': 'd44fb07063e9a8bd8a209ddce35b40d8a56c8d02', 'test_file': 'pandas/tests/frame/test_join.py'}, '35': {'python_version': '3.8.3', 'buggy_commit_id': 'a7dd3ea', 'fixed_commit_id': 'f10ec595eccaf86a9f52fe9683e1181a51ba675b', 'test_file': 'pandas/tests/indexes/multi/test_get_level_values.py'}, '161': {'python_version': '3.8.3', 'buggy_commit_id': 'a818281', 'fixed_commit_id': 'ca5198a6daa7757e398112a17ccadc9e7d078d96', 'test_file': 'pandas/tests/series/test_missing.py'}, '102': {'python_version': '3.8.3', 'buggy_commit_id': 'efaadd5', 'fixed_commit_id': '765d8db7eef1befef33f4c99d3e206d26e8444c8', 'test_file': 'pandas/tests/frame/test_constructors.py'}, '69': {'python_version': '3.8.3', 'buggy_commit_id': '426d445', 'fixed_commit_id': '948f95756c79543bb089a94a85e73011a3730b2d', 'test_file': 'pandas/tests/indexes/test_numeric.py'}, '56': {'python_version': '3.8.3', 'buggy_commit_id': '9e69040', 'fixed_commit_id': 'dafec63f2e138d0451dae5b37edea2e83f9adc8a', 'test_file': 'pandas/tests/indexing/test_scalar.py'}, '105': {'python_version': '3.8.3', 'buggy_commit_id': '7e6125a', 'fixed_commit_id': 'cb5f9d1ff407f5ccef7c717e0c23bbd6ed96cf5f', 'test_file': 'pandas/tests/arithmetic/test_period.py'}, '51': {'python_version': '3.8.3', 'buggy_commit_id': '4800ab4', 'fixed_commit_id': 'ea1d8fadb95fbc7cafe036274006228400817fd4', 'test_file': 'pandas/tests/reshape/merge/test_merge.py'}, '58': {'python_version': '3.8.3', 'buggy_commit_id': '634a41f', 'fixed_commit_id': '16684f2affaf901b42a12e50f9c29e7c034ad7ea', 'test_file': 'pandas/tests/arrays/categorical/test_constructors.py'}, '133': {'python_version': '3.8.3', 'buggy_commit_id': '343544d', 'fixed_commit_id': 'c983d52e3a3a8a191359814417f375b1dc8b04c1', 'test_file': 'pandas/tests/frame/test_missing.py'}, '67': {'python_version': '3.8.3', 'buggy_commit_id': 'c3e32d7', 'fixed_commit_id': '1996b17599731b889895b0e1edf758588c068fbb', 'test_file': 'pandas/tests/frame/indexing/test_indexing.py'}, '93': {'python_version': '3.8.3', 'buggy_commit_id': '425c2fb', 'fixed_commit_id': 'bde25278ccf4fb2d751c5e99e24b2270e0d62ef7', 'test_file': 'pandas/tests/indexes/period/test_indexing.py;'}, '134': {'python_version': '3.8.3', 'buggy_commit_id': 'da1401b', 'fixed_commit_id': 'b1eb97bdfe17f477600eef19e82d65480457bbf5', 'test_file': 'pandas/tests/tseries/holiday/test_calendar.py'}, '94': {'python_version': '3.8.3', 'buggy_commit_id': '8803056', 'fixed_commit_id': '613df15047887957f5964d2a6ce59ea20b0c4c91', 'test_file': 'pandas/tests/indexes/datetimes/test_constructors.py'}, '60': {'python_version': '3.8.3', 'buggy_commit_id': '6bc2dca', 'fixed_commit_id': 'fcf7258c19b0a6a712f33fb0bcefdae426be7e7f', 'test_file': 'pandas/tests/window/test_grouper.py'}, '34': {'python_version': '3.8.3', 'buggy_commit_id': '02a134b', 'fixed_commit_id': 'cf9ec7854ecb80709804178e769425f02ddf8c64', 'test_file': 'pandas/tests/resample/test_datetime_index.py'}, '160': {'python_version': '3.8.3', 'buggy_commit_id': '489d1ff', 'fixed_commit_id': 'fb62fcf91c874e9c24fa83693c4e6e613f35f864', 'test_file': 'pandas/tests/test_expressions.py'}, '33': {'python_version': '3.8.3', 'buggy_commit_id': '03dacc1', 'fixed_commit_id': '89d8aba76a2bb930e520590d145e3d67b2046e39', 'test_file': 'pandas/tests/arrays/integer/test_function.py'}, '158': {'python_version': '3.8.3', 'buggy_commit_id': 'a76df79', 'fixed_commit_id': 'b1c871ce4b5e76b3cffe1ebd4216d36379872352', 'test_file': 'pandas/tests/series/test_alter_axes.py'}, '167': {'python_version': '3.8.3', 'buggy_commit_id': '6af6d51', 'fixed_commit_id': '226398224d260d908a1f3d0f23c16fa9ffc8f9b0', 'test_file': 'pandas/tests/indexes/datetimes/test_partial_slicing.py'}, '151': {'python_version': '3.8.3', 'buggy_commit_id': '6110608', 'fixed_commit_id': '5a227a410c520ceec2d94369a44e2ab774a40dc3', 'test_file': 'pandas/tests/arrays/test_numpy.py'}, '169': {'python_version': '3.8.3', 'buggy_commit_id': '4d9016e', 'fixed_commit_id': '01babb590cb15ef5c6e9ad890ea580a5112e6999', 'test_file': 'pandas/tests/frame/test_quantile.py'}, '156': {'python_version': '3.8.3', 'buggy_commit_id': '42d6ee7', 'fixed_commit_id': '05cc95971e56b503d4df9911a44cd60a7b74cc79', 'test_file': 'pandas/tests/sparse/frame/test_frame.py'}, '20': {'python_version': '3.8.3', 'buggy_commit_id': 'ea09d50', 'fixed_commit_id': '92afd5c2c08216e4e9c80eb6b92b1660f91846e0', 'test_file': 'pandas/tests/tseries/offsets/test_yqm_offsets.py'}, '18': {'python_version': '3.8.3', 'buggy_commit_id': 'e008a0a', 'fixed_commit_id': 'cb71376385c33270fa1922aec9eb6c49de4336f4', 'test_file': 'pandas/tests/window/test_base_indexer.py'}, '27': {'python_version': '3.8.3', 'buggy_commit_id': '6658d89', 'fixed_commit_id': '13dc13f12c0fca943979cde065b7484bb0e40d66', 'test_file': 'pandas/tests/indexes/datetimes/test_to_period.py'}, '9': {'python_version': '3.8.3', 'buggy_commit_id': 'c557ab5', 'fixed_commit_id': 'ebb727e5cd8865a7f5d6cfb4b22d3278b6bf5e6b', 'test_file': 'pandas/tests/indexes/categorical/test_indexing.py'}, '145': {'python_version': '3.8.3', 'buggy_commit_id': '3bd222d', 'fixed_commit_id': 'f08a1e62e31fc11e7e5bd7bec72b7e6d86473423', 'test_file': 'pandas/tests/frame/test_arithmetic.py'}, '11': {'python_version': '3.8.3', 'buggy_commit_id': '1c88e6a', 'fixed_commit_id': 'b7f061c3d24df943e16918ad3932e767f5639a38', 'test_file': 'pandas/tests/reshape/test_concat.py'}, '142': {'python_version': '3.8.3', 'buggy_commit_id': '7721f31', 'fixed_commit_id': '65815e6f33e25991e3d40a53c581ffb3c7daf70f', 'test_file': 'pandas/tests/series/test_analytics.py'}, '7': {'python_version': '3.8.3', 'buggy_commit_id': '27f365d', 'fixed_commit_id': '64336ff8414f8977ff94adb9a5bc000a3a4ef454', 'test_file': 'pandas/tests/frame/indexing/test_indexing.py'}, '29': {'python_version': '3.8.3', 'buggy_commit_id': '6e3537d', 'fixed_commit_id': '4334482c348c3adc69683c8332295e22092c1b57', 'test_file': 'pandas/tests/arrays/interval/test_interval.py;pandas/tests/series/methods/test_convert_dtypes.py'}, '16': {'python_version': '3.8.3', 'buggy_commit_id': 'f159734', 'fixed_commit_id': '74e8607cb163b76ccf272ac72ae6b7848fe930c8', 'test_file': 'pandas/tests/arithmetic/test_period.py'}, '129': {'python_version': '3.8.3', 'buggy_commit_id': '5b580fb', 'fixed_commit_id': '82c9547ddcaf2fd70e00f1368731f14a03bbac88', 'test_file': 'pandas/tests/arithmetic/test_timedelta64.py'}, '42': {'python_version': '3.8.3', 'buggy_commit_id': 'b3a0fe4', 'fixed_commit_id': '05780a760400e42ce1b00200dd8204ae4f94044a', 'test_file': 'pandas/tests/util/test_assert_frame_equal.py;pandas/tests/util/test_assert_series_equal.py'}, '89': {'python_version': '3.8.3', 'buggy_commit_id': '0dc317f', 'fixed_commit_id': 'feaa5033b7810f7775fd4806c27b2f9f1e9b5051', 'test_file': 'pandas/tests/frame/test_reshape.py'}, '116': {'python_version': '3.8.3', 'buggy_commit_id': '9333e3d', 'fixed_commit_id': 'c4fa6a52f7737aecda08f6b0f2d6c27476298ae1', 'test_file': 'pandas/tests/reshape/merge/test_merge_asof.py'}, '45': {'python_version': '3.8.3', 'buggy_commit_id': '74c5306', 'fixed_commit_id': '74f6579941fbe71cf7c033f53977047ac872e469', 'test_file': 'pandas/tests/frame/test_constructors.py'}, '111': {'python_version': '3.8.3', 'buggy_commit_id': '28715a7', 'fixed_commit_id': '27836e93dc3c9d55c60282ccb15c88c42a340d87', 'test_file': 'pandas/tests/indexing/test_categorical.py;pandas/tests/indexing/test_floats.py'}, '73': {'python_version': '3.8.3', 'buggy_commit_id': 'f1d7ac6', 'fixed_commit_id': '6f93898d32c0f1fdb382d1e9dee434c158998374', 'test_file': 'pandas/tests/frame/test_arithmetic.py'}, '118': {'python_version': '3.8.3', 'buggy_commit_id': '6f1accd', 'fixed_commit_id': '76e39ebcf584042fab4f224a6bd2c903bb0c8aff', 'test_file': 'pandas/tests/reshape/test_melt.py'}, '87': {'python_version': '3.8.3', 'buggy_commit_id': '641346c', 'fixed_commit_id': 'a890239b7020dec714d9819b718d83f786bfda34', 'test_file': 'pandas/tests/reshape/test_pivot.py'}, '127': {'python_version': '3.8.3', 'buggy_commit_id': 'f7d6b58', 'fixed_commit_id': '710d82c0d393c9031e469ec0371660d8187b7dc3', 'test_file': 'pandas/tests/series/test_timeseries.py'}, '80': {'python_version': '3.8.3', 'buggy_commit_id': 'd0d93db', 'fixed_commit_id': '351760c0655b6c383e449cf857b9a718e3545229', 'test_file': 'pandas/tests/arrays/sparse/test_arithmetics.py'}, '74': {'python_version': '3.8.3', 'buggy_commit_id': '9a211aa', 'fixed_commit_id': '839e7f1416148caff518a5b75327a2480a2bbbb4', 'test_file': 'pandas/tests/indexes/timedeltas/test_constructors.py'}, '120': {'python_version': '3.8.3', 'buggy_commit_id': '2b0cac7', 'fixed_commit_id': 'c5a1f9e2c373ced9ef2f02ab64d11eaa7b4248f2', 'test_file': 'pandas/tests/groupby/test_categorical.py'}, '6': {'python_version': '3.8.3', 'buggy_commit_id': '21a10d1', 'fixed_commit_id': '8cd8ed3657e52ad9f67e17b7f5c20f7340ab6a2c', 'test_file': 'pandas/tests/groupby/test_size.py'}, '28': {'python_version': '3.8.3', 'buggy_commit_id': '40fd73a', 'fixed_commit_id': 'ef9b9387c88cf12b20dd8656dfedfc236e0f3352', 'test_file': 'pandas/tests/test_strings.py'}, '143': {'python_version': '3.8.3', 'buggy_commit_id': 'c13c13b', 'fixed_commit_id': 'df918becf698741861da0e9b7e810d477b0eb194', 'test_file': 'pandas/tests/frame/test_indexing.py;pandas/tests/indexes/test_range.py'}, '17': {'python_version': '3.8.3', 'buggy_commit_id': '1e5ff23', 'fixed_commit_id': 'afb04645b5b3361814f7d00ef68ce8d68e19ddb8', 'test_file': 'pandas/tests/indexes/datetimes/test_insert.py'}, '144': {'python_version': '3.8.3', 'buggy_commit_id': 'b106108', 'fixed_commit_id': 'ffe6cfdbf82d663c3f77567bde11f1666de1df38', 'test_file': 'pandas/tests/plotting/test_series.py'}, '1': {'python_version': '3.8.3', 'buggy_commit_id': '3fd150c', 'fixed_commit_id': 'e41ee47a90bb1d8a1fa28fcefcd45ed8ef5cb946', 'test_file': 'pandas/tests/dtypes/test_dtypes.py'}, '10': {'python_version': '3.8.3', 'buggy_commit_id': 'de8ca78', 'fixed_commit_id': 'e1ee2b0679e5999c993a787606d30e75faaba7a2', 'test_file': 'pandas/tests/series/methods/test_update.py'}, '19': {'python_version': '3.8.3', 'buggy_commit_id': '17dc6b0', 'fixed_commit_id': 'c6a1638bcd99df677a8f76f036c0b30027eb243c', 'test_file': 'pandas/tests/indexing/multiindex/test_loc.py;pandas/tests/indexing/multiindex/test_slice.py;pandas/tests/series/indexing/test_getitem.py'}, '26': {'python_version': '3.8.3', 'buggy_commit_id': '13dc13f', 'fixed_commit_id': '70ca24680d3e51fa4b957366e8093b3cc755462d', 'test_file': 'pandas/tests/arrays/categorical/test_analytics.py'}, '8': {'python_version': '3.8.3', 'buggy_commit_id': 'ddbeca6', 'fixed_commit_id': 'd09f20e29bdfa82f5efc071986e2633001d552f6', 'test_file': 'pandas/tests/frame/methods/test_replace.py'}, '21': {'python_version': '3.8.3', 'buggy_commit_id': '4071c3b', 'fixed_commit_id': '56d0934092b8296c90f940c56fce3b731e0de81b', 'test_file': 'pandas/tests/series/indexing/test_boolean.py;pandas/tests/series/indexing/test_getitem.py'}, '75': {'python_version': '3.8.3', 'buggy_commit_id': '2038d7a', 'fixed_commit_id': '9a211aae9f710db23c9113aea0251e2758904755', 'test_file': 'pandas/tests/indexes/period/test_indexing.py'}, '81': {'python_version': '3.8.3', 'buggy_commit_id': 'b529857', 'fixed_commit_id': '339edcdb7ecc6edc6fde1b7d1413dbb746d2bcca', 'test_file': 'pandas/tests/arrays/test_integer.py'}, '121': {'python_version': '3.8.3', 'buggy_commit_id': 'ad4c4d5', 'fixed_commit_id': '958756af5cb40658e975a70d29089b68aea93040', 'test_file': 'pandas/tests/frame/test_replace.py'}, '119': {'python_version': '3.8.3', 'buggy_commit_id': '3f69d62', 'fixed_commit_id': 'e0bd4d5dd07cc481cb52de3cf3c7bf199cb2df07', 'test_file': 'pandas/tests/reshape/test_pivot.py'}, '86': {'python_version': '3.8.3', 'buggy_commit_id': '55cfabb', 'fixed_commit_id': 'f792d8c50ee456aa8aa2ae406d8e6b8843f45614', 'test_file': 'pandas/tests/reshape/test_pivot.py'}, '72': {'python_version': '3.8.3', 'buggy_commit_id': 'a9b61a9', 'fixed_commit_id': '0c50950f2a7e32887eff6be5979f09772091e1de', 'test_file': 'pandas/tests/frame/indexing/test_categorical.py'}, '126': {'python_version': '3.8.3', 'buggy_commit_id': '29be383', 'fixed_commit_id': 'e639af2afd18b90ab9063df9c1927ae1f357a418', 'test_file': 'pandas/tests/frame/test_combine_concat.py'}, '44': {'python_version': '3.8.3', 'buggy_commit_id': '96d22d4', 'fixed_commit_id': '50817487ce5b1a2c4896495509e2b53e22fa3212', 'test_file': 'pandas/tests/indexes/test_base.py;pandas/tests/indexing/test_loc.py'}, '110': {'python_version': '3.8.3', 'buggy_commit_id': 'cceef8e', 'fixed_commit_id': '96bb151fe1a5b812ecab400adcd297d14fd0e0e4', 'test_file': 'pandas/tests/indexing/test_categorical.py'}, '43': {'python_version': '3.8.3', 'buggy_commit_id': '81149fb', 'fixed_commit_id': 'be7bfe6ab7ae2cba056f61dea6c3b0226bf80082', 'test_file': 'pandas/tests/frame/test_arithmetic.py'}, '128': {'python_version': '3.8.3', 'buggy_commit_id': '794a1c2', 'fixed_commit_id': '112e6b8d054f9adc1303138533ed6506975f94db', 'test_file': 'pandas/tests/io/json/test_readlines.py'}, '88': {'python_version': '3.8.3', 'buggy_commit_id': '698920f', 'fixed_commit_id': '586bcb16023ae870b0ad7769f6d9077903705486', 'test_file': 'pandas/tests/reshape/test_pivot.py'}, '117': {'python_version': '3.8.3', 'buggy_commit_id': 'fc100fe', 'fixed_commit_id': 'f98d2b6587b74c9a640b062d94911b199d962119', 'test_file': 'pandas/tests/series/test_analytics.py'}, '153': {'python_version': '3.8.3', 'buggy_commit_id': 'ae22b80', 'fixed_commit_id': '0c0a0cfbadcf01864d499599712edc9022eea12e', 'test_file': 'pandas/tests/io/formats/test_to_csv.py'}, '38': {'python_version': '3.8.3', 'buggy_commit_id': 'c81d90f', 'fixed_commit_id': 'e7ee418fa7a519225203fef23481c5fa35834dc3', 'test_file': 'pandas/tests/frame/test_reshape.py'}, '154': {'python_version': '3.8.3', 'buggy_commit_id': '3f5b5c4', 'fixed_commit_id': 'e0c63b4cfaa821dfe310f4a8a1f84929ced5f5bd', 'test_file': 'pandas/tests/groupby/test_groupby.py'}, '36': {'python_version': '3.8.3', 'buggy_commit_id': 'cb41651', 'fixed_commit_id': '51f114b9882a5cf819efddb8be74524814f437e1', 'test_file': 'pandas/tests/dtypes//test_missing.py'}, '162': {'python_version': '3.8.3', 'buggy_commit_id': '341043d', 'fixed_commit_id': '640d9e1f5fe8ab64d1f6496b8216c28185e53225', 'test_file': 'pandas/tests/reshape/test_pivot.py'}, '31': {'python_version': '3.8.3', 'buggy_commit_id': '45c13a9', 'fixed_commit_id': '8267427bfe567eec9a098aa8c071dddcc1d289f9', 'test_file': 'pandas/tests/groupby/test_function.py'}, '165': {'python_version': '3.8.3', 'buggy_commit_id': '9fe8a0f', 'fixed_commit_id': '9b1c005142fed227081dd454eab1a414168d458e', 'test_file': 'pandas/tests/arithmetic/test_datetime64.py'}, '131': {'python_version': '3.8.3', 'buggy_commit_id': '73745be', 'fixed_commit_id': 'bf5848f111c92fc5c6c11a93a3bc2480f138f1b1', 'test_file': 'pandas/tests/series/test_datetime_values.py'}, '91': {'python_version': '3.8.3', 'buggy_commit_id': '5c12d4f', 'fixed_commit_id': 'cb9a1c7d0319c34a97247973ca96af53ead8033a', 'test_file': 'pandas/tests/arrays/test_timedeltas.py'}, '65': {'python_version': '3.8.3', 'buggy_commit_id': '2f70e41', 'fixed_commit_id': '2f9a44635bd8d468cf008f2855ce2dcfb9e90586', 'test_file': 'pandas/tests/io/parser/test_encoding.py'}, '136': {'python_version': '3.8.3', 'buggy_commit_id': '3954fa7', 'fixed_commit_id': '6241b9d3b3b8fd688cf32e45539719f1b9ec25c1', 'test_file': 'pandas/tests/reshape/merge/test_merge_asof.py'}, '62': {'python_version': '3.8.3', 'buggy_commit_id': '46a77f6', 'fixed_commit_id': '74dad82827e9b13552df2d6d3fbbeb901821b53f', 'test_file': 'pandas/tests/indexing/test_indexing.py'}, '96': {'python_version': '3.8.3', 'buggy_commit_id': '5e488a0', 'fixed_commit_id': '6d67cf9f02dd22cc870fd407f569197512700203', 'test_file': 'pandas/tests/indexes/datetimes/test_date_range.py'}, '109': {'python_version': '3.8.3', 'buggy_commit_id': '8b39de1', 'fixed_commit_id': '68b3eb4f5a7fbc223accbbeddbf03ec8ea31af00', 'test_file': 'pandas/tests/arrays/categorical/test_analytics.py'}, '100': {'python_version': '3.8.3', 'buggy_commit_id': '8806ed7', 'fixed_commit_id': '2b1b3da4c68fdaf9637d12706c5ba3de1a9b20de', 'test_file': 'pandas/tests/frame/methods/test_pct_change.py'}, '54': {'python_version': '3.8.3', 'buggy_commit_id': '25443f0', 'fixed_commit_id': '00e8e4ab0c5e4c7bfb3e356e660d9f088d4a82a4', 'test_file': 'pandas/tests/dtypes/test_dtypes.py'}, '107': {'python_version': '3.8.3', 'buggy_commit_id': '47ac4b3', 'fixed_commit_id': 'fa4949f27ccfbc255bb8dbcd5ec5464b8663f1d2', 'test_file': 'pandas/tests/frame/test_combine_concat.py'}, '98': {'python_version': '3.8.3', 'buggy_commit_id': '8105a7e', 'fixed_commit_id': '09e4b780f09c5aa72bb2a6ae2832612f81dc047f', 'test_file': 'pandas/tests/indexes/period/test_constructors.py'}, '138': {'python_version': '3.8.3', 'buggy_commit_id': '3dcbec5', 'fixed_commit_id': 'c59c2df94e5563819a824f49fa6f55636bdb4445', 'test_file': 'pandas/tests/reshape/test_qcut.py'}, '53': {'python_

In [43]:
print(len(dict_of_bugs))

169

In [46]:
df=pd.DataFrame.from_dict(dict_of_bugs, orient='index')
df.index.name = 'bug_id'
df.head()

,python_version,buggy_commit_id,fixed_commit_id,test_file
bug_id,,,,
135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py
61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py
95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py
132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py
59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py

In [47]:
df.reset_index(inplace=True)
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bug_id           169 non-null    str
 1   python_version   169 non-null    str
 2   buggy_commit_id  169 non-null    str
 3   fixed_commit_id  169 non-null    str
 4   test_file        169 non-null    str
dtypes: str(5)
memory usage: 6.7 KB

In [53]:
dict_of_bug_patches = {}
for bug in list_of_pandas_bugs:
    dict_of_bug_patches[bug.name] = {}
    with open(bug/"bug_patch.txt", 'r') as f:
        bug_patch_info = f.read()
        bug_patch_lines = bug_patch_info.splitlines()
        #for line in bug_patch_lines:
            #key, value = line.split("=")
            #value = value.strip().strip('"')#cleaning the value by stripping whitespace and quotes
        dict_of_bug_patches[bug.name]=bug_patch_lines

print(dict_of_bug_patches['135'])

['diff --git a/pandas/core/groupby/ops.py b/pandas/core/groupby/ops.py', 'index 00e7012b4..e6f4f2f05 100644', '--- a/pandas/core/groupby/ops.py', '+++ b/pandas/core/groupby/ops.py', '@@ -672,7 +672,13 @@ class BaseGrouper:', '                 pass', '             else:', '                 raise', '-            return self._aggregate_series_pure_python(obj, func)', '+        except TypeError as err:', '+            if "ndarray" in str(err):', "+                # raised in libreduction if obj's values is no ndarray", '+                pass', '+            else:', '+                raise', '+        return self._aggregate_series_pure_python(obj, func)', ' ', '     def _aggregate_series_fast(self, obj, func):', '         func = self._is_builtin_func(func)']

In [55]:
rows = []
for bug in list_of_pandas_bugs:
    bug_data = {"bug_id": bug.name}
    # Read bug.info

    with open(bug / "bug.info", "r") as f:
        for line in f:
            key, value = line.split("=")
            bug_data[key] = value.strip().strip('"')

    # Read raw patch

    with open(bug / "bug_patch.txt", "r") as f:
            bug_data["patch"] = f.read()
    rows.append(bug_data)

df = pd.DataFrame(rows)

df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...

In [56]:
df["modified_files"] = df["patch"].str.findall(r"diff --git a/(.*?) b/")
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py]
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py]
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py]
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]"
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py]

In [57]:
df["num_files_changed"] = df["modified_files"].str.len()
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1

In [66]:
def check_line_added(raw_patch):
    total = 0

    for line in raw_patch.split('\n'):
        if line.startswith("+") and not line.startswith("+++"):
            total += 1
    return total

df["lines_added"] = df["patch"].apply(check_line_added)

df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1

In [68]:
df["lines_removed"]=df["patch"].apply(lambda x: sum(1 for line in x.split('\n') if line.startswith("-") and not line.startswith("---")))
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1

In [70]:
df["num_hunks"]=df["patch"].str.count("@@")
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2

In [72]:
df["patch_length"] = df["patch"].str.len()

df["has_comment"] = df["patch"].apply(

    lambda x: "#" in x

)
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2,706,True
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2,531,True
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4,969,True
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4,1148,False
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2,571,True

In [80]:
import re
df["declared_classes_in_patch"]=df["patch"].apply(lambda x: re.findall(r"class\s+([A-Za-z_]\w*)",x))
df

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2,706,True,[BaseGrouper]
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2,531,True,[Series]
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4,969,True,[]
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4,1148,False,[Series]
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2,571,True,[_Rolling_and_Expanding]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,140,3.8.3,3b19e1d,4375daffeed16531bae3fdaf85324b590d1dcb59,pandas/tests/groupby/test_apply.py,diff --git a/pandas/core/groupby/generic.py b/...,[pandas/core/groupby/generic.py],1,3,1,2,552,True,[]
165,14,3.8.3,e7b23d4,dd71064327721c1ec7366000f357b0c08bcec4d2,pandas/tests/arithmetic/test_datetime64.py;pan...,diff --git a/pandas/core/ops/dispatch.py b/pan...,"[pandas/core/ops/dispatch.py, pandas/tests/ari...",2,16,2,4,1389,True,[]
166,22,3.8.3,38b669a,299e27da8a75d02d84870c1ca5971f4dd0f046e6,pandas/tests/window/test_base_indexer.py,diff --git a/pandas/core/window/common.py b/pa...,"[pandas/core/window/common.py, pandas/core/win...",2,7,3,6,1607,True,"[BASEINDEXER_WHITELIST, _Rolling_and_Expanding..."
167,149,3.8.3,0d69d91,fa1364d1299a53093bc704f9c34c595b602a568b,pandas/tests/io/test_gcs.py,diff --git a/pandas/io/parquet.py b/pandas/io/...,[pandas/io/parquet.py],1,4,4,4,1178,True,[FastParquetImpl]
168,25,3.8.3,ecc3b2e,73d614403759831814ef7ab83ef1e4aaa645b33a,pandas/tests/indexes/datetimes/test_misc.py,diff --git a/pandas/core/arrays/datetimes.py b...,[pandas/core/arrays/datetimes.py],1,5,1,2,679,False,[]

In [83]:
df["declared_functions_in_patch"]=df["patch"].str.findall(r"def\s+([A-Za-z_]\w*)")
df

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2,706,True,[BaseGrouper],[_aggregate_series_fast]
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2,531,True,[Series],[]
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4,969,True,[],"[_period_array_cmp, wrapper, _period_array_cmp]"
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4,1148,False,[Series],"[nanstd, nanvar]"
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2,571,True,[_Rolling_and_Expanding],[_get_corr]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,140,3.8.3,3b19e1d,4375daffeed16531bae3fdaf85324b590d1dcb59,pandas/tests/groupby/test_apply.py,diff --git a/pandas/core/groupby/generic.py b/...,[pandas/core/groupby/generic.py],1,3,1,2,552,True,[],[_recast_datetimelike_result]
165,14,3.8.3,e7b23d4,dd71064327721c1ec7366000f357b0c08bcec4d2,pandas/tests/arithmetic/test_datetime64.py;pan...,diff --git a/pandas/core/ops/dispatch.py b/pan...,"[pandas/core/ops/dispatch.py, pandas/tests/ari...",2,16,2,4,1389,True,[],"[should_series_dispatch, id_func, names]"
166,22,3.8.3,38b669a,299e27da8a75d02d84870c1ca5971f4dd0f046e6,pandas/tests/window/test_base_indexer.py,diff --git a/pandas/core/window/common.py b/pa...,"[pandas/core/window/common.py, pandas/core/win...",2,7,3,6,1607,True,"[BASEINDEXER_WHITELIST, _Rolling_and_Expanding...","[get_weighted_roll_func, validate_baseindexer_..."
167,149,3.8.3,0d69d91,fa1364d1299a53093bc704f9c34c595b602a568b,pandas/tests/io/test_gcs.py,diff --git a/pandas/io/parquet.py b/pandas/io/...,[pandas/io/parquet.py],1,4,4,4,1178,True,[FastParquetImpl],[get_engine]
168,25,3.8.3,ecc3b2e,73d614403759831814ef7ab83ef1e4aaa645b33a,pandas/tests/indexes/datetimes/test_misc.py,diff --git a/pandas/core/arrays/datetimes.py b...,[pandas/core/arrays/datetimes.py],1,5,1,2,679,False,[],[]

In [85]:
df["number_of_declared_classes_in_patch"] = df["declared_classes_in_patch"].str.len()
df

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2,706,True,[BaseGrouper],[_aggregate_series_fast],1
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2,531,True,[Series],[],1
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4,969,True,[],"[_period_array_cmp, wrapper, _period_array_cmp]",0
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4,1148,False,[Series],"[nanstd, nanvar]",1
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2,571,True,[_Rolling_and_Expanding],[_get_corr],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,140,3.8.3,3b19e1d,4375daffeed16531bae3fdaf85324b590d1dcb59,pandas/tests/groupby/test_apply.py,diff --git a/pandas/core/groupby/generic.py b/...,[pandas/core/groupby/generic.py],1,3,1,2,552,True,[],[_recast_datetimelike_result],0
165,14,3.8.3,e7b23d4,dd71064327721c1ec7366000f357b0c08bcec4d2,pandas/tests/arithmetic/test_datetime64.py;pan...,diff --git a/pandas/core/ops/dispatch.py b/pan...,"[pandas/core/ops/dispatch.py, pandas/tests/ari...",2,16,2,4,1389,True,[],"[should_series_dispatch, id_func, names]",0
166,22,3.8.3,38b669a,299e27da8a75d02d84870c1ca5971f4dd0f046e6,pandas/tests/window/test_base_indexer.py,diff --git a/pandas/core/window/common.py b/pa...,"[pandas/core/window/common.py, pandas/core/win...",2,7,3,6,1607,True,"[BASEINDEXER_WHITELIST, _Rolling_and_Expanding...","[get_weighted_roll_func, validate_baseindexer_...",4
167,149,3.8.3,0d69d91,fa1364d1299a53093bc704f9c34c595b602a568b,pandas/tests/io/test_gcs.py,diff --git a/pandas/io/parquet.py b/pandas/io/...,[pandas/io/parquet.py],1,4,4,4,1178,True,[FastParquetImpl],[get_engine],1
168,25,3.8.3,ecc3b2e,73d614403759831814ef7ab83ef1e4aaa645b33a,pandas/tests/indexes/datetimes/test_misc.py,diff --git a/pandas/core/arrays/datetimes.py b...,[pandas/core/arrays/datetimes.py],1,5,1,2,679,False,[],[],0

In [86]:
df["number_of_declared_functions_in_patch"] = df["declared_functions_in_patch"].str.len()
df

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2,706,True,[BaseGrouper],[_aggregate_series_fast],1,1
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2,531,True,[Series],[],1,0
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4,969,True,[],"[_period_array_cmp, wrapper, _period_array_cmp]",0,3
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4,1148,False,[Series],"[nanstd, nanvar]",1,2
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2,571,True,[_Rolling_and_Expanding],[_get_corr],1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,140,3.8.3,3b19e1d,4375daffeed16531bae3fdaf85324b590d1dcb59,pandas/tests/groupby/test_apply.py,diff --git a/pandas/core/groupby/generic.py b/...,[pandas/core/groupby/generic.py],1,3,1,2,552,True,[],[_recast_datetimelike_result],0,1
165,14,3.8.3,e7b23d4,dd71064327721c1ec7366000f357b0c08bcec4d2,pandas/tests/arithmetic/test_datetime64.py;pan...,diff --git a/pandas/core/ops/dispatch.py b/pan...,"[pandas/core/ops/dispatch.py, pandas/tests/ari...",2,16,2,4,1389,True,[],"[should_series_dispatch, id_func, names]",0,3
166,22,3.8.3,38b669a,299e27da8a75d02d84870c1ca5971f4dd0f046e6,pandas/tests/window/test_base_indexer.py,diff --git a/pandas/core/window/common.py b/pa...,"[pandas/core/window/common.py, pandas/core/win...",2,7,3,6,1607,True,"[BASEINDEXER_WHITELIST, _Rolling_and_Expanding...","[get_weighted_roll_func, validate_baseindexer_...",4,4
167,149,3.8.3,0d69d91,fa1364d1299a53093bc704f9c34c595b602a568b,pandas/tests/io/test_gcs.py,diff --git a/pandas/io/parquet.py b/pandas/io/...,[pandas/io/parquet.py],1,4,4,4,1178,True,[FastParquetImpl],[get_engine],1,1
168,25,3.8.3,ecc3b2e,73d614403759831814ef7ab83ef1e4aaa645b33a,pandas/tests/indexes/datetimes/test_misc.py,diff --git a/pandas/core/arrays/datetimes.py b...,[pandas/core/arrays/datetimes.py],1,5,1,2,679,False,[],[],0,0

In [89]:
df["modified_files"]=df["patch"].str.findall(r"diff --git a/(.*?) b/")
df.head()

,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch
0,135,3.8.3,0df22b6,f41219179de69fed5c2a4b7df821394af1aa6559,pandas/tests/extension/decimal/test_decimal.py,diff --git a/pandas/core/groupby/ops.py b/pand...,[pandas/core/groupby/ops.py],1,7,1,2,706,True,[BaseGrouper],[_aggregate_series_fast],1,1
1,61,3.8.3,74dad82,f7e2b74f1bcc1d1cbebbc42481e33f0abb2843dc,pandas/tests/indexing/test_indexing.py,diff --git a/pandas/core/series.py b/pandas/co...,[pandas/core/series.py],1,1,1,2,531,True,[Series],[],1,0
2,95,3.8.3,036dc88,c99dfea33612f44e97c2365f78c0ca6d5754a1bc,pandas/tests/arithmetic/test_period.py,diff --git a/pandas/core/arrays/period.py b/pa...,[pandas/core/arrays/period.py],1,0,6,4,969,True,[],"[_period_array_cmp, wrapper, _period_array_cmp]",0,3
3,132,3.8.3,221c8a7,bd8f07fb29d2ac819f4c8e8e1b8e6d40f8b0f40c,pandas/tests/reductions/test_reductions.py,diff --git a/pandas/core/nanops.py b/pandas/co...,"[pandas/core/nanops.py, pandas/core/series.py]",2,6,2,4,1148,False,[Series],"[nanstd, nanvar]",1,2
4,59,3.8.3,292a993,8dd9fabd2ad9104e747084437b9ad436d5be087a,pandas/tests/window/test_pairwise.py,diff --git a/pandas/core/window/rolling.py b/p...,[pandas/core/window/rolling.py],1,1,1,2,571,True,[_Rolling_and_Expanding],[_get_corr],1,1

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 17 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   bug_id                                 169 non-null    str
 1   python_version                         169 non-null    str
 2   buggy_commit_id                        169 non-null    str
 3   fixed_commit_id                        169 non-null    str
 4   test_file                              169 non-null    str
 5   patch                                  169 non-null    str
 6   modified_files                         169 non-null    object
 7   num_files_changed                      169 non-null    int64
 8   lines_added                            169 non-null    int64
 9   lines_removed                          169 non-null    int64
 10  num_hunks                              169 non-null    int64
 11  patch_length                           169 non-null    int64
 12  has_comment                            169 non-null    bool
 13  declared_classes_in_patch              169 non-null    object
 14  declared_functions_in_patch            169 non-null    object
 15  number_of_declared_classes_in_patch    169 non-null    int64
 16  number_of_declared_functions_in_patch  169 non-null    int64
dtypes: bool(1), int64(7), object(3), str(6)
memory usage: 21.4+ KB

In [92]:
from pathlib import Path
import pandas as pd
import re

DATA_DIR = Path("../data/raw/bugsinpy/projects")

all_rows = []

for project in DATA_DIR.iterdir():

    if not project.is_dir():
        continue

    print(f"Processing {project.name}...")

    bugs_dir = project / "bugs"

    if not bugs_dir.exists():
        print(f"Skipping {project.name} (no bugs folder)")
        continue

    for bug in bugs_dir.iterdir():

        if not bug.is_dir():
            continue

        # Read bug.info
        bug_info = {}

        with open(bug / "bug.info", "r") as f:
            for line in f.read().splitlines():
                key, value = line.split("=", 1)
                bug_info[key] = value.strip().strip('"')


        # Read patch
        patch = ""

        if (bug / "bug_patch.txt").exists():
            with open(bug / "bug_patch.txt", "r") as f:
                patch = f.read()

        elif (bug / "bug.patch").exists():
            with open(bug / "bug.patch", "r") as f:
                patch = f.read()

        else:
            print(f"Warning: No patch file for {project.name}/{bug.name}")


        # Store one row
        row = {
            "project": project.name,
            "bug_id": bug.name,
            **bug_info,#unpack the bug_info dictionary into the row
            "patch": patch,
        }

        all_rows.append(row)

# Create DataFrame

df = pd.DataFrame(all_rows)

# Feature Engineering

df["modified_files"] = df["patch"].str.findall(
    r"diff --git a/(.*?) b/"
)

df["num_files_changed"] = df["modified_files"].apply(len)

df["lines_added"] = df["patch"].apply(
    lambda x: sum(
        1
        for line in x.splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )
)

df["lines_removed"] = df["patch"].apply(
    lambda x: sum(
        1
        for line in x.splitlines()
        if line.startswith("-") and not line.startswith("---")
    )
)

df["num_hunks"] = df["patch"].str.count(r"@@")

df["patch_length"] = df["patch"].apply(
    lambda x: len(x.splitlines())
)

df["has_comment"] = df["patch"].str.contains(
    r"#|//|/\*|\*/",
    regex=True
)

df["declared_classes_in_patch"] = df["patch"].apply(
    lambda x: re.findall(
        r"class\s+([A-Za-z_]\w*)",
        x
    )
)

df["declared_functions_in_patch"] = df["patch"].apply(
    lambda x: re.findall(
        r"def\s+([A-Za-z_]\w*)",
        x
    )
)

df["number_of_declared_classes_in_patch"] = (
    df["declared_classes_in_patch"].apply(len)
)

df["number_of_declared_functions_in_patch"] = (
    df["declared_functions_in_patch"].apply(len)
)

print(df.info())
df.head()

Processing keras...
Processing thefuck...
Processing PySnooper...
Processing luigi...
Processing cookiecutter...
Processing scrapy...
Processing ansible...
Processing tornado...
Processing tqdm...
Processing fastapi...
Processing sanic...
Processing matplotlib...
Processing youtube-dl...
Processing httpie...
Processing spacy...
Processing black...
Processing pandas...
<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   project                                501 non-null    str
 1   bug_id                                 501 non-null    str
 2   python_version                         501 non-null    str
 3   buggy_commit_id                        501 non-null    str
 4   fixed_commit_id                        459 non-null    str
 5   test_file                              501 non-null    str
 6   patch                                  501 non-null    str
 7   pythonpath                             49 non-null     str
 8   fixed_commit_id                        42 non-null     str
 9   modified_files                         501 non-null    object
 10  num_files_changed                      501 non-null    int64
 11  lines_added                            501 non-null    int64
 12  lines_removed                          501 non-null    int64
 13  num_hunks                              501 non-null    int64
 14  patch_length                           501 non-null    int64
 15  has_comment                            501 non-null    bool
 16  declared_classes_in_patch              501 non-null    object
 17  declared_functions_in_patch            501 non-null    object
 18  number_of_declared_classes_in_patch    501 non-null    int64
 19  number_of_declared_functions_in_patch  501 non-null    int64
dtypes: bool(1), int64(7), object(3), str(9)
memory usage: 75.0+ KB
None

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,fixed_commit_id,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,NaN,NaN,[keras/callbacks.py],1,11,6,10,66,False,"[ReduceLROnPlateau, ReduceLROnPlateau, ReduceL...","[__init__, in_cooldown]",5,2
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,NaN,NaN,[keras/preprocessing/image.py],1,16,3,6,45,True,"[ImageDataGenerator, NumpyArrayIterator, Direc...",[],3,0
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,NaN,NaN,"[keras/engine/training.py, keras/utils/data_ut...",2,22,4,10,69,True,"[Model, Model, Model, Model, Sequence]",[__iter__],5,1
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,NaN,NaN,[keras/preprocessing/text.py],1,13,4,2,30,False,[],[text_to_word_sequence],0,1
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,NaN,NaN,"[keras/backend/cntk_backend.py, keras/backend/...",5,48,19,38,236,True,"[Conv2DTranspose, Conv2DTranspose, Conv2DTrans...","[in_top_k, conv2d_transpose, conv2d_transpose,...",5,22

In [93]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   project                                501 non-null    str
 1   bug_id                                 501 non-null    str
 2   python_version                         501 non-null    str
 3   buggy_commit_id                        501 non-null    str
 4   fixed_commit_id                        459 non-null    str
 5   test_file                              501 non-null    str
 6   patch                                  501 non-null    str
 7   pythonpath                             49 non-null     str
 8   fixed_commit_id                        42 non-null     str
 9   modified_files                         501 non-null    object
 10  num_files_changed                      501 non-null    int64
 11  lines_added                            501 non-null    int64
 12  lines_removed                          501 non-null    int64
 13  num_hunks                              501 non-null    int64
 14  patch_length                           501 non-null    int64
 15  has_comment                            501 non-null    bool
 16  declared_classes_in_patch              501 non-null    object
 17  declared_functions_in_patch            501 non-null    object
 18  number_of_declared_classes_in_patch    501 non-null    int64
 19  number_of_declared_functions_in_patch  501 non-null    int64
dtypes: bool(1), int64(7), object(3), str(9)
memory usage: 75.0+ KB

In [95]:
#fixed_commit_id repeats, verifying if it is unique or not
for c in df.columns:
    print(repr(c))

'project'
'bug_id'
'python_version'
'buggy_commit_id'
'fixed_commit_id'
'test_file'
'patch'
'pythonpath'
'fixed_commit_id '
'modified_files'
'num_files_changed'
'lines_added'
'lines_removed'
'num_hunks'
'patch_length'
'has_comment'
'declared_classes_in_patch'
'declared_functions_in_patch'
'number_of_declared_classes_in_patch'
'number_of_declared_functions_in_patch'

In [96]:
#the bug.info key needs to be cleaned up, as it has some extra spaces and newlines. Let's clean it up.
from pathlib import Path
import pandas as pd
import re

DATA_DIR = Path("../data/raw/bugsinpy/projects")

all_rows = []

for project in DATA_DIR.iterdir():

    if not project.is_dir():
        continue

    print(f"Processing {project.name}...")

    bugs_dir = project / "bugs"

    if not bugs_dir.exists():
        print(f"Skipping {project.name} (no bugs folder)")
        continue

    for bug in bugs_dir.iterdir():

        if not bug.is_dir():
            continue


        # Read bug.info
        bug_info = {}

        with open(bug / "bug.info", "r") as f:
            for line in f.read().splitlines():

                if "=" not in line:
                    continue

                key, value = line.split("=", 1)

                key = key.strip()# FIX
                value = value.strip().strip('"')

                bug_info[key] = value


        # Read patch
        patch = ""

        if (bug / "bug_patch.txt").exists():
            with open(bug / "bug_patch.txt", "r") as f:
                patch = f.read()

        elif (bug / "bug.patch").exists():
            with open(bug / "bug.patch", "r") as f:
                patch = f.read()

        row = {
            "project": project.name,
            "bug_id": bug.name,
            **bug_info,
            "patch": patch,
        }

        all_rows.append(row)


# Create DataFrame

df = pd.DataFrame(all_rows)


# Feature Engineering

df["modified_files"] = df["patch"].str.findall(
    r"diff --git a/(.*?) b/"
)

df["num_files_changed"] = df["modified_files"].apply(len)

df["lines_added"] = df["patch"].apply(
    lambda x: sum(
        1
        for line in x.splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )
)

df["lines_removed"] = df["patch"].apply(
    lambda x: sum(
        1
        for line in x.splitlines()
        if line.startswith("-") and not line.startswith("---")
    )
)

df["num_hunks"] = df["patch"].str.count(r"@@")

df["patch_length"] = df["patch"].apply(
    lambda x: len(x.splitlines())
)

df["has_comment"] = df["patch"].str.contains(
    r"#|//|/\*|\*/",
    regex=True
)

df["declared_classes_in_patch"] = df["patch"].apply(
    lambda x: re.findall(
        r"class\s+([A-Za-z_]\w*)",
        x
    )
)

df["declared_functions_in_patch"] = df["patch"].apply(
    lambda x: re.findall(
        r"def\s+([A-Za-z_]\w*)",
        x
    )
)

df["number_of_declared_classes_in_patch"] = (
    df["declared_classes_in_patch"].apply(len)
)

df["number_of_declared_functions_in_patch"] = (
    df["declared_functions_in_patch"].apply(len)
)

# Remove accidental whitespace from column names (extra safety)
df.columns = df.columns.str.strip()

print(df.info())
df.head()

Processing keras...
Processing thefuck...
Processing PySnooper...
Processing luigi...
Processing cookiecutter...
Processing scrapy...
Processing ansible...
Processing tornado...
Processing tqdm...
Processing fastapi...
Processing sanic...
Processing matplotlib...
Processing youtube-dl...
Processing httpie...
Processing spacy...
Processing black...
Processing pandas...
<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   project                                501 non-null    str
 1   bug_id                                 501 non-null    str
 2   python_version                         501 non-null    str
 3   buggy_commit_id                        501 non-null    str
 4   fixed_commit_id                        501 non-null    str
 5   test_file                              501 non-null    str
 6   patch                                  501 non-null    str
 7   pythonpath                             49 non-null     str
 8   modified_files                         501 non-null    object
 9   num_files_changed                      501 non-null    int64
 10  lines_added                            501 non-null    int64
 11  lines_removed                          501 non-null    int64
 12  num_hunks                              501 non-null    int64
 13  patch_length                           501 non-null    int64
 14  has_comment                            501 non-null    bool
 15  declared_classes_in_patch              501 non-null    object
 16  declared_functions_in_patch            501 non-null    object
 17  number_of_declared_classes_in_patch    501 non-null    int64
 18  number_of_declared_functions_in_patch  501 non-null    int64
dtypes: bool(1), int64(7), object(3), str(8)
memory usage: 71.1+ KB
None

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,NaN,[keras/callbacks.py],1,11,6,10,66,False,"[ReduceLROnPlateau, ReduceLROnPlateau, ReduceL...","[__init__, in_cooldown]",5,2
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,NaN,[keras/preprocessing/image.py],1,16,3,6,45,True,"[ImageDataGenerator, NumpyArrayIterator, Direc...",[],3,0
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,NaN,"[keras/engine/training.py, keras/utils/data_ut...",2,22,4,10,69,True,"[Model, Model, Model, Model, Sequence]",[__iter__],5,1
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,NaN,[keras/preprocessing/text.py],1,13,4,2,30,False,[],[text_to_word_sequence],0,1
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,NaN,"[keras/backend/cntk_backend.py, keras/backend/...",5,48,19,38,236,True,"[Conv2DTranspose, Conv2DTranspose, Conv2DTrans...","[in_top_k, conv2d_transpose, conv2d_transpose,...",5,22

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   project                                501 non-null    str
 1   bug_id                                 501 non-null    str
 2   python_version                         501 non-null    str
 3   buggy_commit_id                        501 non-null    str
 4   fixed_commit_id                        501 non-null    str
 5   test_file                              501 non-null    str
 6   patch                                  501 non-null    str
 7   pythonpath                             49 non-null     str
 8   modified_files                         501 non-null    object
 9   num_files_changed                      501 non-null    int64
 10  lines_added                            501 non-null    int64
 11  lines_removed                          501 non-null    int64
 12  num_hunks                              501 non-null    int64
 13  patch_length                           501 non-null    int64
 14  has_comment                            501 non-null    bool
 15  declared_classes_in_patch              501 non-null    object
 16  declared_functions_in_patch            501 non-null    object
 17  number_of_declared_classes_in_patch    501 non-null    int64
 18  number_of_declared_functions_in_patch  501 non-null    int64
dtypes: bool(1), int64(7), object(3), str(8)
memory usage: 71.1+ KB

In [101]:
df[df["pythonpath"].notna()]

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch
17,keras,1,3.7.3,331d5b0102ab0cc79cece1f03cc551d8105db3c9,8e23a3ec47a2ccbf6cdd222a80886c6b9f17264f,tests/keras/initializers_test.py,diff --git a/keras/backend/tensorflow_backend....,,"[keras/backend/tensorflow_backend.py, keras/ba...",4,84,71,34,329,True,"[RandomNormal, RandomUniform, TruncatedNormal,...","[update, update_add, update_sub, get_variable_...",10,28
39,keras,2,3.7.3,2f55055a9f053b35fa721d3eb75dd07ea5a5f1e3,c24d16af155e20976bdf61e468ba760408e676ff,tests/keras/backend/backend_test.py,diff --git a/keras/backend/numpy_backend.py b/...,,[keras/backend/numpy_backend.py],1,6,0,2,17,False,[],"[l2_normalize, in_top_k, binary_crossentropy]",0,3
113,cookiecutter,1,3.6.9,c15633745df6abdb24e02746b82aadb20b8cdf8c,7f6804c4953a18386809f11faf4d86898570debc,tests/test_generate_context.py,diff --git a/cookiecutter/generate.py b/cookie...,cookiecutter/build/lib/,[cookiecutter/generate.py],1,1,1,2,13,True,[],[generate_context],0,1
114,cookiecutter,4,3.6.9,9568ab6ecd2d6836646006c59473c4a4ac0dee04,457a1a4e862aab4102b644ff1d2b2e2b5a766b3c,tests/test_hooks.py,diff --git a/cookiecutter/exceptions.py b/cook...,cookiecutter/build/lib/,"[cookiecutter/exceptions.py, cookiecutter/gene...",3,20,6,14,85,True,"[InvalidModeException, FailedHookException]","[copy_without_render, generate_files, run_scri...",2,7
115,cookiecutter,3,3.6.9,5c282f020a8db7e5e7c4e7b51b010556ca31fb7f,7129d474206761a6156925db78eee4b62a0e3944,tests/test_read_user_choice.py,diff --git a/cookiecutter/prompt.py b/cookiecu...,cookiecutter/build/lib/,[cookiecutter/prompt.py],1,1,1,2,13,False,[],[read_user_choice],0,1
116,cookiecutter,2,3.6.9,d7e7b28811e474e14d1bed747115e47dcdd15ba3,90434ff4ea4477941444f1e83313beb414838535,tests/test_hooks.py,diff --git a/cookiecutter/hooks.py b/cookiecut...,cookiecutter/build/lib/,[cookiecutter/hooks.py],1,9,5,4,35,False,[],"[find_hook, run_script, run_hook]",0,3
157,ansible,18,3.6.9,bb1256ca9aa4c22225dbeef0ef23a20fa9388b2f,056aac1e3012d0e65991b73f2478b844b7cbdfc8,test/units/cli/test_galaxy.py,diff --git a/lib/ansible/cli/galaxy.py b/lib/a...,ansible/build/lib/,[lib/ansible/cli/galaxy.py],1,3,3,6,31,True,"[GalaxyCLI, GalaxyCLI, GalaxyCLI]",[execute_info],3,1
158,ansible,9,3.6.9,9276dd2007a73172ed99ab5a56cded4298d3cd2b,6f1bb37feb81acd99157f5ba0933fecd747015a2,test/units/modules/packaging/os/test_redhat_su...,diff --git a/lib/ansible/modules/packaging/os/...,ansible/build/lib/,[lib/ansible/modules/packaging/os/redhat_subsc...,1,5,3,4,26,False,[Rhsm],[main],1,1
159,ansible,11,3.6.9,da07b98b7a433493728ddb7ac7efbd20b8988776,52f3ce8a808f943561803bd664e695fed1841fe8,test/units/modules/network/ios/test_ios_banner.py,diff --git a/lib/ansible/modules/network/ios/i...,ansible/build/lib/,[lib/ansible/modules/network/ios/ios_banner.py],1,16,16,8,67,False,[],"[map_obj_to_commands, map_obj_to_commands, map...",0,6
160,ansible,7,3.6.9,cd146b836e032df785ecd9eb711c6ef23c2228b8,4ec1437212b2fb3c313e44ed5a76b105f2151622,test/units/modules/network/eos/test_eos_vlans.py,diff --git a/lib/ansible/module_utils/network/...,ansible/build/lib/,[lib/ansible/module_utils/network/eos/config/v...,1,5,4,2,26,False,[],[generate_commands],0,1
161,ansible,16,3.6.9,2a9964ede8b2b77a62a005f6f5abc964b2819b0e,93d9d640380252084855885ad27873b4377898ec,test/units/module_utils/facts/hardware/test_li...,diff --git a/lib/ansible/module_utils/facts/ha...,ansible/build/lib/,[lib/ansible/module_utils/facts/hardware/linux...,2,7,6,6,44,True,[LinuxHardware],[],1,0
162,ansible,6,3.6.9,90898132e456ee1993db99a1531379f1b98ee915,4881af2e7e0506ada0225fd764e874e20569d5b2,test/units/galaxy/test_collection_install.py,diff --git a/lib/ansible/galaxy/collection.py ...,ansible/build/lib/,[lib/ansible/galaxy/collection.py],1,17,8,6,50,True,"[CollectionRequirement, CollectionRequirement]",[_get_collection_info],2,1
163,ansible,17,3.6.9,9cb47832d15c61884b30d70f9d4e0f816b064b05,b38cb37728df76e0529243bdce694b18ca0e1163,test/units/module_utils/facts/test_facts.py,diff --git a/lib/ansible/module_utils/facts/ha...,ansible/build/lib/,[lib/ansible/module_utils/facts/hardware/linux...,1,13,0,6,38,True,"[LinuxHardware, LinuxHardware, LinuxHardware]","[populate, _replace_octal_escapes_helper, _rep...",3,4
164,ansible,1,3.6.9,25c5388fdec9e56517a93feb5e8d485680946c25,343ffaa18b63c92e182b16c3ad84b8d81ca4df69,test/units/galaxy/test_collection.py,diff --git a/lib/ansible/galaxy/collection.py ...,ansible/build/lib/,[lib/ansible/galaxy/collection.py],1,5,0,2,16,False,[],[verify_collections],0,1
165,ansible,10,3.6.9,e368f788f71c338cd3f049d5d6bdc643a51c0514,a4b59d021368285490f7cda50c11ac4f7a8030b5,test/units/modules/system/test_pamd.py,diff --git a/lib/ansible/modules/system/pamd.p...,ansible/build/lib/,[lib/ansible/modules/system/pamd.py],1,4,1,4,23,False,"[PamdRule, PamdService]",[__init__],2,1
166,ansible,8,3.6.9,81378b3e744cd0d13b33d18a4f8a38aeb8a6e97a,fc7980af9a42676913b4054163570ee438b82e9c,test/units/plugins/shell/test_powershell.py,diff --git a/lib/ansible/plugins/shell/powersh...,ansible/build/lib/,[lib/ansible/plugins/shell/powershell.py],1,8,8,4,34,True,[ShellModule],"[join_path, get_remote_filename]",1,2
167,ansible,4,3.6.9,d91658ec0c8434c82c3ef98bfe9eb4e1027a43a3,18a66e291dad71128a32d662aa808213acefe0e9,test/units/playbook/test_collectionsearch.py,diff --git a/lib/ansible/playbook/collectionse...,ansible/build/lib/,[lib/ansible/playbook/collectionsearch.py],1,15,1,6,39,True,"[CollectionSearch, CollectionSearch]","[_ensure_default_collection, _ensure_default_c...",2,3
168,ansible,15,3.6.9,b1e8a6c1cbd2a668b462995487b819ef7dd8ba4b,68de182555b185737353e780882159a3d213908c,test/units/modules/network/eos/test_eos_eapi.py,diff --git a/lib/ansible/modules/network/eos/e...,ansible/build/lib/,[lib/ansible/modules/network/eos/eos_eapi.py],1,1,1,2,13,False,[],[map_obj_to_commands],0,1
169,ansible,3,3.6.9,70219df9056ffb1e2766f572fbe71f7a1800c9f5,9d48884e36fb4fd9551f000b87d264383de74e75,test/units/module_utils/test_distribution_vers...,diff --git a/lib/ansible/module_utils/facts/sy...,ansible/build/lib/,[lib/ansible/module_utils/facts/system/distrib...,1,2,1,2,14,True,[DistributionFiles],[],1,0
170,ansible,12,3.6.9,05e2e1806162393d76542a75c2520c7d61c2d855,2fa8f9cfd80daf32c7d222190edf7cfc7234582a,test/units/plugins/lookup/test_env.py,diff --git a/lib/ansible/plugins/lookup/env.py...,ansible/build/lib/,[lib/ansible/plugins/lookup/env.py],1,2,3,4,23,False,"[LookupModule, LookupModule]",[],2,0
171,ansible,2,3.6.9,de59b17c7f69d5cfb72479b71776cc8b97e29a6b,5b9418c06ca6d51507468124250bb58046886be6,test/units/utils/test_version.py,diff --git a/lib/ansible/utils/version.py b/li...,ansible/build/lib/,[lib/ansible/utils/version.py],1,8,8,4,42,False,"[_Alpha, _Numeric, _Numeric, SemanticVersion]","[__gt__, __le__, __gt__, __ge__, __gt__, __le_...",4,8
172,ansible,13,3.6.9,41472ee3878be215af8b933b2b04b4a72b9165ca,694ef5660d45fcb97c9beea5b2750f6eadcf5e93,test/units/cli/test_galaxy.py,diff --git a/lib/ansible/cli/galaxy.py b/lib/a...,ansible/build/lib/,"[lib/ansible/cli/galaxy.py, lib/ansible/galaxy...",2,15,3,6,54,True,"[GalaxyCLI, GalaxyCLI]",[_get_collection_info],2,1
173,ansible,5,3.6.9,2af76f16be8cf2239daaec4c2f31c3dcb4e3469e,3c3ffc09c203d1b2262f6a319cceadd727749761,test/units/module_utils/common/validation/test...,diff --git a/lib/ansible/module_utils/common/v...,ansible/build/lib/,[lib/ansible/module_utils/common/validation.py...,2,5,4,6,38,False,[],"[check_required_arguments, test_check_mutually...",0,5
174,ansible,14,3.6.9,a1ab093ddbd32f1002cbf6d6f184c7d0041d890d,7acae62fa849481b2a5e2e2d56961c5e1dcea96c,test/units/galaxy/test_api.py,diff --git a/lib/ansible/galaxy/api.py b/lib/a...,ansible/build/lib/,[lib/ansible/galaxy/api.py],1,15,3,4,41,True,[GalaxyAPI],[],1,0
175,tornado,9,3.7.0,c9d2a3fa573987629ad576e991c2f3b65f4daab4,86cc31f52992fb9d11f92de6fd5496842fea2265,tornado/test/httputil_test.py,diff --git a/tornado/httputil.py b/tornado/htt...,,[tornado/httputil.py],1,2,0,2,13,True,[],[url_concat],0,1
176,tornado,11,3.7.0,79ef301eb05cac82c075198e502d94dad296f6aa,1131c9b50a6a4c0868d0d6fa5e0be077cf8fd1ca,tornado/test/httpserver_test.py,diff --git a/tornado/http1connection.py b/torn...,,[tornado/http1connection.py],1,1,1,2,13,False,[HTTP1Connection],[],1,0
177,tornado,7,3.7.0,fa3409179588536f2f743d16e537f6f9827fa92f,a3b44cd701e0e82693363701bc0346b0125d2362,tornado/test/ioloop_test.py,diff --git a/tornado/ioloop.py b/tornado/ioloo...,,[tornado/ioloop.py],1,7,3,4,28,True,[IOLoop],[set_default_executor],1,1
178,tornado,16,3.7.0,b450ff270df0395ee80f4ee5896a92bfe7f9b6ae,d1676810ef5972c4defb0a710a1d8f8a0018983b,tornado/test/gen_test.py,diff --git a/tornado/gen.py b/tornado/gen.py\n...,,[tornado/gen.py],1,8,0,4,26,True,"[WaitIterator, WaitIterator]",[],2,0
179,tornado,6,3.7.0,fb74e4816ccfa7fc6a7abd8c8aab1f415cfc1b13,2905ee4fb3c283d40b10f609359e189c83a0dc06,tornado/test/asyncio_test.py,diff --git a/tornado/ioloop.py b/tornado/ioloo...,,"[tornado/ioloop.py, tornado/platform/asyncio.py]",2,16,2,8,54,True,"[IOLoop, BaseAsyncIOLoop, BaseAsyncIOLoop]","[configure, add_handler]",3,2
180,tornado,1,3.7.0,6a5a0bfa370b6c0d3dbbf9589a560a98202d2baa,4677c54cc18bbfbdf0f4dadf11610fab6203fd63,tornado/test/websocket_test.py,diff --git a/tornado/websocket.py b/tornado/we...,,[tornado/websocket.py],1,9,2,6,36,False,"[WebSocketHandler, WebSocketProtocol, _PerMess...","[on_connection_close, _receive_frame_loop, set...",5,5
181,tornado,10,3.7.0,ecd8968c5135b810cd607b5902dda2cd32122b39,5931d913b4ea250891a0b582f1f8b2901b868c79,tornado/test/websocket_test.py,diff --git a/tornado/web.py b/tornado/web.py\n...,,"[tornado/web.py, tornado/websocket.py]",2,13,0,4,35,True,"[RequestHandler, WebSocketHandler]","[_break_cycles, _break_cycles, send_error]",2,3
182,tornado,8,3.7.0,34c43f4775971ab9b2b8ed43356f218add6387b2,5d4a9ab26372efd255bbb29fde55c41395ed17b1,tornado/test/websocket_test.py,diff --git a/tornado/websocket.py b/tornado/we...,,[tornado/websocket.py],1,8,0,2,19,False,[WebSocketProtocol13],[accept_connection],1,1
183,tornado,4,3.7.0,a8420fc681c5423d072978f00eab4d0645057d16,db529031a1e1a6e951826aba0b7d0b18f05cd4c7,tornado/test/web_test.py,diff --git a/tornado/web.py b/tornado/web.py\n...,,[tornado/web.py],1,12,4,2,33,True,[StaticFileHandler],[],1,0
184,tornado,15,3.7.0,fdfaf3dffa49479c7461050eacca07bc5ee8d207,ecb3ea7543cc942659faf3d2144853018afa6139,tornado/test/web_test.py,diff --git a/setup.py b/setup.py\nindex 9b81b2...,,"[setup.py, tornado/web.py]",2,8,3,4,33,True,[StaticFileHandler],[],1,0
185,tornado,3,3.7.0,940fd87fe9145d1154c8457221f86d56ea063c65,aa622e724f80e0f7fcee369f75d69d1db13d72f2,tornado/test/httpclient_test.py,diff --git a/tornado/httpclient.py b/tornado/h...,,[tornado/httpclient.py],1,7,2,2,21,True,[AsyncHTTPClient],[fetch],1,1
186,tornado,12,3.7.0,4ee9ba94de11aaa4f932560fa2b3d8ceb8c61d2a,301f52b532c071a0d2fec1eb7c23f2714bb38567,tornado/test/auth_test.py,diff --git a/tornado/auth.py b/tornado/auth.py...,,[tornado/auth.py],1,9,4,6,38,True,"[FacebookGraphMixin, FacebookGraphMixin]",[_oauth_signature],2,1
187,tornado,2,3.7.0,2ca8821d006f6693f920a4b183a3a7c985a5c8ad,4f486a4aec746e9d66441600ee3b0743228b061c,tornado/test/httpclient_test.py,diff --git a/tornado/http1connection.py b/torn...,,[tornado/http1connection.py],1,4,1,2,16,False,[HTTP1Connection],[],1,0
188,tornado,13,3.7.0,d7d9c467cda38f4c9352172ba7411edc29a85196,34903f9e1a99441b2729bbe6f1d65d46cf352ea7,tornado/test/http1connection_test.py,diff --git a/tornado/http1connection.py b/torn...,,"[tornado/http1connection.py, tornado/test/runt...",2,4,1,4,27,True,[HTTP1Connection],[],1,0
189,tornado,5,3.7.0,2d4053daa56c609d642b214399e046671d4a593e,886643965b5cb782503d8d7b374b7a794ec2077b,tornado/test/ioloop_test.py,diff --git a/tornado/ioloop.py b/tornado/ioloo...,,[tornado/ioloop.py],1,21,1,2,33,True,[PeriodicCallback],[_update_next],1,1
190,tornado,14,3.7.0,81ee310adcd905fbdf7c98d9fb6ef0c5a46026c2,1d02ed606f1c52636462633d009bdcbaac644331,tornado/test/ioloop_test.py,diff --git a/tornado/ioloop.py b/tornado/ioloo...,,[tornado/ioloop.py],1,1,1,2,13,False,[IOLoop],[],1,0
191,tqdm,9,3.6.9,9da1d5d116aec7a23d8f6dc22d5e23ecb1c40a7c,d877c1dfb4739852105f7b967a8fceb869ac5042,tqdm/tests/tests_tqdm.py,diff --git a/tqdm/_tqdm.py b/tqdm/_tqdm.py\nin...,tqdm/build/lib/,[tqdm/_tqdm.py],1,8,8,12,62,True,"[tqdm, tqdm, tqdm, tqdm, tqdm]","[format_sizeof, __len__, __iter__]",5,3
192,tqdm,7,3.6.9,caefe02fd6f3165e5634460ab20caf4c60400120,4efd35246c924236f34d8130b1055a3c3ba78605,tqdm/tests/tests_main.py,diff --git a/tqdm/_main.py b/tqdm/_main.py\nin...,tqdm/build/lib/,[tqdm/_main.py],1,1,1,2,13,True,[],[posix_pipe],0,1
193,tqdm,6,3.6.9,a4b9c86db548b2d0dbb5af7a6bbdc26ab47e1eec,6dad2e89019317e875c46d5a3a82a811ad6de2f9,tqdm/tests/tests_synchronisation.py,diff --git a/tqdm/_tqdm.py b/tqdm/_tqdm.py\nin...,tqdm/build/lib/,[tqdm/_tqdm.py],1,1,1,2,13,False,[tqdm],[__enter__],1,1
194,tqdm,1,3.6.9,8cc777fe8401a05d07f2c97e65d15e4460feab88,c0dcf39b046d1b4ff6de14ac99ad9a1b10487512,tqdm/tests/tests_contrib.py,diff --git a/tqdm/contrib/__init__.py b/tqdm/c...,tqdm/build/lib/,[tqdm/contrib/__init__.py],1,1,1,2,13,False,[],"[tenumerate, _tzip]",0,2
195,tqdm,8,3.6.9,08b8ad1ff3bd003ef8309faaa0cc108ffa40317d,cae9d139c6df5614be3bf6e25ccbd600ee3286dc,tqdm/tests/tests_tqdm.py,diff --git a/tqdm/_tqdm.py b/tqdm/_tqdm.py\nin...,tqdm/build/lib/,[tqdm/_tqdm.py],1,1,1,2,13,True,[tqdm],[],1,0
196,tqdm,4,3.6.9,03b347646492131d889871939b40457d29147216,964dee631d0ed30e2f799b42fc58ba5e73795a08,tqdm/tests/tests_tqdm.py,diff --git a/tqdm/_tqdm.py b/tqdm/_tqdm.py\nin...,tqdm/build/lib/,[tqdm/_tqdm.py],1,2,1,2,14,True,[tqdm],[],1,0
197,tqdm,3,3.6.9,c2599e3cd6087429f48bae34347ec5d2473c8392,73962a47026dd980ac0758820efc9c41cbf938e0,tqdm/tests/tests_tqdm.py,diff --git a/tqdm/_tqdm.py b/tqdm/_tqdm.py\nin...,tqdm/build/lib/,[tqdm/_tqdm.py],1,11,0,2,22,True,[tqdm],"[__bool__, __nonzero__, __len__]",1,3
198,tqdm,2,3.6.9,bef86db56654d271838b145ad77f7040a73a7b4d,127af5caf19e7d29c346f5ca8a9c7ef3004b664b,tqdm/tests/tests_tqdm.py,diff --git a/tqdm/std.py b/tqdm/std.py\nindex ...,tqdm/build/lib/,"[tqdm/std.py, tqdm/utils.py]",2,6,6,6,41,True,"[tqdm, tqdm]",[disp_trim],2,1
199,tqdm,5,3.6.9,19b08ab34fdbfa0275bc5cb2430436c724c7e759,4f340697af69b71850aad496387c9c5aa1904136,tqdm/tests/tests_tqdm.py,diff --git a/tqdm/_tqdm.py b/tqdm/_tqdm.py\nin...,tqdm/build/lib/,[tqdm/_tqdm.py],1,7,6,4,37,True,"[tqdm, tqdm]",[],2,0

In [102]:
pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp314-cp314-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Applications/BugTriageAgent/python-bug-triage-assistant/.venv/lib/python3.14/site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.0.51-cp314-cp314-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 5.1 MB/s  0:00:00 eta 0:00:01
Downloading psycopg2_binary-2.9.12-cp314-cp314-macosx_11_0_arm64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 3.2 MB/s  0:00:01 eta 0:00:01
Installing collected packages: sqlalchemy, psycopg2-binary
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [psycopg2-binary]
Successfully installed psycopg2-binary-2.9.12 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [104]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://krishnapriyagitalaxmi@localhost:5432/bugsinpy")
engine

Engine(postgresql+psycopg2://krishnapriyagitalaxmi@localhost:5432/bugsinpy)

In [105]:
df.to_sql("bug_dataset", engine, if_exists="replace", index=False)

501

In [106]:
test=pd.read_sql("SELECT * FROM bug_dataset LIMIT 5", engine)
test

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,lines_added,lines_removed,num_hunks,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,None,{keras/callbacks.py},1,11,6,10,66,False,"{ReduceLROnPlateau,ReduceLROnPlateau,ReduceLRO...","{__init__,in_cooldown}",5,2
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,None,{keras/preprocessing/image.py},1,16,3,6,45,True,"{ImageDataGenerator,NumpyArrayIterator,Directo...",{},3,0
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,None,"{keras/engine/training.py,keras/utils/data_uti...",2,22,4,10,69,True,"{Model,Model,Model,Model,Sequence}",{__iter__},5,1
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,None,{keras/preprocessing/text.py},1,13,4,2,30,False,{},{text_to_word_sequence},0,1
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,None,"{keras/backend/cntk_backend.py,keras/backend/t...",5,48,19,38,236,True,"{Conv2DTranspose,Conv2DTranspose,Conv2DTranspo...","{in_top_k,conv2d_transpose,conv2d_transpose,_p...",5,22

In [108]:
test=pd.read_sql("select project,bug_id, num_files_Changed,lines_added from bug_dataset limit 5", engine)
test

  project bug_id  num_files_changed  lines_added
0   keras     32                  1           11
1   keras     35                  1           16
2   keras     34                  2           22
3   keras     33                  1           13
4   keras     20                  5           48