In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/processed/bug_dataset.csv")
df.head()

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,...,patch_length,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch,exception_types,num_exception_types,modified_modules,num_modified_modules
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,NaN,['keras/callbacks.py'],1,...,66,False,"['ReduceLROnPlateau', 'ReduceLROnPlateau', 'Re...","['__init__', 'in_cooldown']",5,2,['ValueError'],1,['keras'],1
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,NaN,['keras/preprocessing/image.py'],1,...,45,True,"['ImageDataGenerator', 'NumpyArrayIterator', '...",[],3,0,['ValueError'],1,['keras/preprocessing'],1
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,NaN,"['keras/engine/training.py', 'keras/utils/data...",2,...,69,True,"['Model', 'Model', 'Model', 'Model', 'Sequence']",['__iter__'],5,1,[],0,"['keras/engine', 'keras/utils']",2
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,NaN,['keras/preprocessing/text.py'],1,...,30,False,[],['text_to_word_sequence'],0,1,[],0,['keras/preprocessing'],1
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,NaN,"['keras/backend/cntk_backend.py', 'keras/backe...",5,...,236,True,"['Conv2DTranspose', 'Conv2DTranspose', 'Conv2D...","['in_top_k', 'conv2d_transpose', 'conv2d_trans...",5,22,['ValueError'],1,"['keras/backend', 'keras/layers', 'keras/utils']",3

# Bug Category Taxonomy

## Objective

The BugsInPy dataset does not provide an explicit bug-type label suitable for supervised machine learning. Therefore, a bug-category taxonomy is introduced to create a new target variable, **`bug_category`**, for the multiclass classification task.

Unlike repository names or exception types, bug categories describe the **underlying nature of the defect** rather than the project in which it occurred or the runtime symptom it produced. This enables the development of a supervised machine learning model that predicts the type of bug represented by a code patch.

---

# Labeling Methodology

Each bug is assigned **one primary bug category** representing the principal defect addressed by the patch.

The assignment is based primarily on the behavior corrected by the bug fix rather than the exception raised or the repository in which the bug occurred.

The following information may be considered during labeling:

- Patch content and code modifications
- Modified files and modules
- Functions and classes involved
- Exception types (supporting evidence only)
- Test file context
- Added or removed validation and error-handling logic

When multiple issues appear within the same patch, the assigned label should represent the **root cause** of the defect rather than secondary consequences.

Ambiguous cases should be flagged for manual review rather than assigned solely from a single extracted feature.

---

# Bug Categories

## 1. Input Validation

Bugs caused by missing, incorrect, or insufficient validation of inputs, parameters, arguments, or values before processing.

**Examples**

- Missing boundary checks
- Invalid parameter acceptance
- Incorrect validation logic
- Missing null or range checks

---

## 2. Type Handling

Bugs involving incorrect assumptions about data types, casting, conversions, compatibility, or handling of unexpected object types.

**Examples**

- String versus numeric handling
- Incorrect type conversions
- Improper handling of `None`
- Type compatibility issues

---

## 3. Collections and Indexing

Bugs involving lists, dictionaries, arrays, iterators, indexes, slicing, keys, or collection manipulation.

**Examples**

- Invalid indexing
- Missing dictionary keys
- Incorrect slicing
- Iterator boundary errors

---

## 4. API and Configuration

Bugs involving incorrect API behavior, configuration handling, default parameters, option processing, or interactions between software components.

**Examples**

- Incorrect API contracts
- Invalid configuration handling
- Unsupported options
- Incorrect default behavior

---

## 5. File, I/O, and Data Processing

Bugs involving files, paths, parsing, serialization, deserialization, encoding, external data formats, or network responses.

**Examples**

- File path handling
- Parsing failures
- Serialization errors
- Encoding issues
- Data loading problems

---

## 6. Date and Time

Bugs involving timestamps, calendars, time zones, datetime conversions, durations, or date parsing.

**Examples**

- Timezone conversion
- Timestamp calculation
- Invalid datetime parsing
- Calendar logic

---

## 7. Numerical and Computational Logic

Bugs involving arithmetic, numerical computation, dimensions, overflow, precision, or mathematical algorithms.

**Examples**

- Overflow
- Precision loss
- Shape mismatches
- Incorrect numerical calculations

---

## 8. Program Logic and State Management

Bugs caused by incorrect control flow, state transitions, lifecycle management, caching, initialization, or general program logic that do not clearly belong to another category.

**Examples**

- Incorrect boolean logic
- State synchronization
- Cache invalidation
- Incorrect initialization
- Lifecycle management
- Faulty algorithm logic

---

## 9. Other / Ambiguous

Bugs for which the available evidence is insufficient to confidently assign one of the defined categories.

This category should be used sparingly and reviewed periodically to determine whether the taxonomy requires refinement.

---

# Category Precedence

When multiple categories appear applicable, the assigned category should represent the **root cause** of the defect rather than its observable symptom.

The recommended precedence is:

1. Input Validation
2. Type Handling
3. Collections and Indexing
4. API and Configuration
5. File, I/O, and Data Processing
6. Date and Time
7. Numerical and Computational Logic
8. Program Logic and State Management
9. Other / Ambiguous

---

# Exception Type vs. Bug Category

Exception types are **not** treated as bug categories.

An exception represents the **runtime symptom** of a defect, whereas the bug category represents the **underlying cause** of the defect.

For example:

| Exception | Bug Category |
|-----------|--------------|
| `ValueError` | Input Validation |
| `ValueError` | Date and Time |
| `KeyError` | Collections and Indexing |
| `TypeError` | Type Handling |

The same exception may occur across multiple bug categories, while a single bug may reference multiple exception types.

Exception types are therefore used as **predictive features** during machine learning rather than as the target variable.

---

# Intended Machine Learning Use

The manually annotated **`bug_category`** column will serve as the target variable (**y**) for a supervised multiclass classification model.

The trained classifier will predict the most likely bug category for previously unseen bug patches using the engineered structural and semantic features extracted during earlier stages of the project.

The predicted bug category will later become additional metadata within the repository-aware retrieval pipeline, where it can be combined with repository information, modified modules, semantic embeddings, and vector similarity search to retrieve the most relevant historical bug fixes before LLM-based debugging assistance.

In [4]:
#adding a ne bu_category column
df['bug_category']=pd.NA
df.head()

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,...,has_comment,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch,exception_types,num_exception_types,modified_modules,num_modified_modules,bug_category
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,NaN,['keras/callbacks.py'],1,...,False,"['ReduceLROnPlateau', 'ReduceLROnPlateau', 'Re...","['__init__', 'in_cooldown']",5,2,['ValueError'],1,['keras'],1,<NA>
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,NaN,['keras/preprocessing/image.py'],1,...,True,"['ImageDataGenerator', 'NumpyArrayIterator', '...",[],3,0,['ValueError'],1,['keras/preprocessing'],1,<NA>
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,NaN,"['keras/engine/training.py', 'keras/utils/data...",2,...,True,"['Model', 'Model', 'Model', 'Model', 'Sequence']",['__iter__'],5,1,[],0,"['keras/engine', 'keras/utils']",2,<NA>
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,NaN,['keras/preprocessing/text.py'],1,...,False,[],['text_to_word_sequence'],0,1,[],0,['keras/preprocessing'],1,<NA>
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,NaN,"['keras/backend/cntk_backend.py', 'keras/backe...",5,...,True,"['Conv2DTranspose', 'Conv2DTranspose', 'Conv2D...","['in_top_k', 'conv2d_transpose', 'conv2d_trans...",5,22,['ValueError'],1,"['keras/backend', 'keras/layers', 'keras/utils']",3,<NA>

In [5]:
BUG_CATEGORIES = [
    "Input Validation",
    "Type Handling",
    "Collections and Indexing",
    "API and Configuration",
    "File, I/O, and Data Processing",
    "Date and Time",
    "Numerical and Computational Logic",
    "Program Logic and State Management",
    "Other / Ambiguous"
]

In [8]:
i = 0

print("Project:", df.loc[i, "project"])
print("Bug ID:", df.loc[i, "bug_id"])
print("Test File:", df.loc[i, "test_file"])
print("Exception Types:", df.loc[i, "exception_types"])
print("Modified Modules:", df.loc[i, "modified_modules"])
print()
print(df.loc[i, "patch"])

Project: keras
Bug ID: 32
Test File: tests/keras/test_callbacks.py
Exception Types: ['ValueError']
Modified Modules: ['keras']

diff --git a/keras/callbacks.py b/keras/callbacks.py
index 8b5ec5f3..eb233de3 100644
--- a/keras/callbacks.py
+++ b/keras/callbacks.py
@@ -898,7 +898,7 @@ class ReduceLROnPlateau(Callback):
             monitored has stopped increasing; in `auto`
             mode, the direction is automatically inferred
             from the name of the monitored quantity.
-        epsilon: threshold for measuring the new optimum,
+        min_delta: threshold for measuring the new optimum,
             to only focus on significant changes.
         cooldown: number of epochs to wait before resuming
             normal operation after lr has been reduced.
@@ -906,16 +906,21 @@ class ReduceLROnPlateau(Callback):
     """

     def __init__(self, monitor='val_loss', factor=0.1, patience=10,
-                 verbose=0, mode='auto', epsilon=1e-4, cooldown=0, min_lr=0):
+                 verbose=0, mode='auto', min_delta=1e-4, cooldown=0, min_lr=0,
+                 **kwargs):
         super(ReduceLROnPlateau, self).__init__()

         self.monitor = monitor
         if factor >= 1.0:
             raise ValueError('ReduceLROnPlateau '
                              'does not support a factor >= 1.0.')
+        if 'epsilon' in kwargs:
+            min_delta = kwargs.pop('epsilon')
+            warnings.warn('`epsilon` argument is deprecated and '
+                          'will be removed, use `min_delta` insted.')
         self.factor = factor
         self.min_lr = min_lr
-        self.epsilon = epsilon
+        self.min_delta = min_delta
         self.patience = patience
         self.verbose = verbose
         self.cooldown = cooldown
@@ -936,10 +941,10 @@ class ReduceLROnPlateau(Callback):
             self.mode = 'auto'
         if (self.mode == 'min' or
            (self.mode == 'auto' and 'acc' not in self.monitor)):
-            self.monitor_op = lambda a, b: np.less(a, b - self.epsilon)
+            self.monitor_op = lambda a, b: np.less(a, b - self.min_delta)
             self.best = np.Inf
         else:
-            self.monitor_op = lambda a, b: np.greater(a, b + self.epsilon)
+            self.monitor_op = lambda a, b: np.greater(a, b + self.min_delta)
             self.best = -np.Inf
         self.cooldown_counter = 0
         self.wait = 0
@@ -967,6 +972,7 @@ class ReduceLROnPlateau(Callback):
                 self.best = current
                 self.wait = 0
             elif not self.in_cooldown():
+                self.wait += 1
                 if self.wait >= self.patience:
                     old_lr = float(K.get_value(self.model.optimizer.lr))
                     if old_lr > self.min_lr:
@@ -978,7 +984,6 @@ class ReduceLROnPlateau(Callback):
                                   'rate to %s.' % (epoch + 1, new_lr))
                         self.cooldown_counter = self.cooldown
                         self.wait = 0
-                self.wait += 1

     def in_cooldown(self):
         return self.cooldown_counter > 0

In [11]:
df.loc[0, "bug_category"] = "Program Logic and State Management"

In [12]:
#adding a label reason column
df['label_reason']=pd.NA
df.head()

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,...,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch,exception_types,num_exception_types,modified_modules,num_modified_modules,bug_category,label_reason
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,NaN,['keras/callbacks.py'],1,...,"['ReduceLROnPlateau', 'ReduceLROnPlateau', 'Re...","['__init__', 'in_cooldown']",5,2,['ValueError'],1,['keras'],1,Program Logic and State Management,<NA>
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,NaN,['keras/preprocessing/image.py'],1,...,"['ImageDataGenerator', 'NumpyArrayIterator', '...",[],3,0,['ValueError'],1,['keras/preprocessing'],1,<NA>,<NA>
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,NaN,"['keras/engine/training.py', 'keras/utils/data...",2,...,"['Model', 'Model', 'Model', 'Model', 'Sequence']",['__iter__'],5,1,[],0,"['keras/engine', 'keras/utils']",2,<NA>,<NA>
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,NaN,['keras/preprocessing/text.py'],1,...,[],['text_to_word_sequence'],0,1,[],0,['keras/preprocessing'],1,<NA>,<NA>
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,NaN,"['keras/backend/cntk_backend.py', 'keras/backe...",5,...,"['Conv2DTranspose', 'Conv2DTranspose', 'Conv2D...","['in_top_k', 'conv2d_transpose', 'conv2d_trans...",5,22,['ValueError'],1,"['keras/backend', 'keras/layers', 'keras/utils']",3,<NA>,<NA>

In [13]:
df.loc[0, "label_reason"] = (
    "Corrects internal callback state and learning-rate reduction logic; "
    "primary defect is incorrect program behavior."
)
df.head()

,project,bug_id,python_version,buggy_commit_id,fixed_commit_id,test_file,patch,pythonpath,modified_files,num_files_changed,...,declared_classes_in_patch,declared_functions_in_patch,number_of_declared_classes_in_patch,number_of_declared_functions_in_patch,exception_types,num_exception_types,modified_modules,num_modified_modules,bug_category,label_reason
0,keras,32,3.7.3,a3d160b9467c99cbb27f9aa0382c759f45c8ee66,709f791af201caaab4aa180bda259989087cfe47,tests/keras/test_callbacks.py,diff --git a/keras/callbacks.py b/keras/callba...,NaN,['keras/callbacks.py'],1,...,"['ReduceLROnPlateau', 'ReduceLROnPlateau', 'Re...","['__init__', 'in_cooldown']",5,2,['ValueError'],1,['keras'],1,Program Logic and State Management,Corrects internal callback state and learning-...
1,keras,35,3.7.3,06eaeebecfb73c23bfd531013ca172ee3bf5069c,738819de0b7e6bc45abed8d0640f02b81c6ac4e9,tests/keras/preprocessing/image_test.py,diff --git a/keras/preprocessing/image.py b/ke...,NaN,['keras/preprocessing/image.py'],1,...,"['ImageDataGenerator', 'NumpyArrayIterator', '...",[],3,0,['ValueError'],1,['keras/preprocessing'],1,<NA>,<NA>
2,keras,34,3.7.3,7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139,4b74fc5418944c9f449eb88ed4b40ada280fa5ca,tests/test_multiprocessing.py,diff --git a/keras/engine/training.py b/keras/...,NaN,"['keras/engine/training.py', 'keras/utils/data...",2,...,"['Model', 'Model', 'Model', 'Model', 'Sequence']",['__iter__'],5,1,[],0,"['keras/engine', 'keras/utils']",2,<NA>,<NA>
3,keras,33,3.7.3,1c9a49781da2101507db23e2014e4e5d16bd2e52,70ad0d6e4a569701ef106058397ad0540ec08340,tests/keras/preprocessing/text_test.py,diff --git a/keras/preprocessing/text.py b/ker...,NaN,['keras/preprocessing/text.py'],1,...,[],['text_to_word_sequence'],0,1,[],0,['keras/preprocessing'],1,<NA>,<NA>
4,keras,20,3.7.3,76da5f0a21ca98e4bf6706e182fb825243e76204,6dd087ab73b09e449144ff17450cc14f981b9ac2,tests/keras/layers/convolutional_test.py,diff --git a/keras/backend/cntk_backend.py b/k...,NaN,"['keras/backend/cntk_backend.py', 'keras/backe...",5,...,"['Conv2DTranspose', 'Conv2DTranspose', 'Conv2D...","['in_top_k', 'conv2d_transpose', 'conv2d_trans...",5,22,['ValueError'],1,"['keras/backend', 'keras/layers', 'keras/utils']",3,<NA>,<NA>